# Copyright (c) 2017-2026 Juancarlo Añez (apalala@gmail.com)
# SPDX-License-Identifier: BSD-4-Clause

StylesPath = .vale/styles
;MinAlertLevel = suggestion
MinAlertLevel = error

Packages = proselint, Microsoft, write-good

Vocab = tatsu

[*]
BasedOnStyles = Vale, proselint, Microsoft, write-good

[*.py]
BasedOnStyles = Vale, proselint, write-good, proselint

proselint.Annotations = ignore
Microsoft.Qutoes = NO


[*.rst]
BasedOnStyles = Vale, Microsoft, proselint, write-good

write-good.E-Prime = NO
write-good.Passive = NO
write-good.ThereIs = NO

Microsoft.Acronyms = NO
Microsoft.Contractions = NO
Microsoft.FirstPerson = NO
Microsoft.HeadingAcronyms = NO
Microsoft.Headings = NO
Microsoft.Passive = NO

;[*.md]
;BasedOnStyles = Vale, Microsoft, proselint
