# Copyright (c) 2017-2026 Juancarlo Añez (apalala@gmail.com)
# SPDX-License-Identifier: BSD-4-Clause
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from .state import ParseStateStack
from ..exceptions import FailedParse
from .infos import RuleInfo


@runtime_checkable
class ParseCtx(Protocol):
    @property
    def states(self) -> ParseStateStack: ...

    def newexcept(
        self,
        item: Any,
        excls: type[FailedParse] = FailedParse,
    ) -> FailedParse: ...

    def _call(self, ri: RuleInfo) -> Any: ...

    def _choice(self) -> Any: ...
    def _constant(self, literal: Any) -> Any: ...
    def _cut(self) -> None: ...
    def _define(self, keys: list[str], addkeys: list[str] | None = None) -> None: ...
    def _gatheropt(self) -> Any: ...
    def _gatherplus(self) -> Any: ...
    def _group(self) -> Any: ...
    def _if(self) -> Any: ...
    def _ifnot(self) -> Any: ...
    def _joinopt(self) -> Any: ...
    def _joinplus(self) -> Any: ...
    def _joinleft(self) -> Any: ...
    def _joinright(self) -> Any: ...
    def _loopopt(self) -> Any: ...
    def _loopplus(self) -> Any: ...
    def _nameadd(self, name: str) -> Any: ...
    def _nameset(self, name: str) -> Any: ...
    def _check_eof(self) -> None: ...
    def _optional(self) -> Any: ...
    def _pattern(self, pattern: str) -> Any: ...
    def _skipto(self) -> Any: ...
    def _token(self, token: str) -> str: ...
    def _void(self) -> None: ...
