<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tatsu</string>
	</array>
	<key>name</key>
	<string>tatsu</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>directive</string>
			<key>match</key>
			<string>@@.*::</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>decorator</string>
			<key>match</key>
			<string>^@.*</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>include directive</string>
			<key>match</key>
			<string>#include\s*::</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.tatsu</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\(\*</string>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment.block.tatsu</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(\b(?:\w|\s|[\-_0-9])+\b)\s*=</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.tatsu.syntax-rule</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\(\*</string>
					<key>comment</key>
					<string>comment blocks</string>
					<key>end</key>
					<string>\*\)</string>
					<key>name</key>
					<string>comment.block.tatsu</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>special characters</string>
					<key>match</key>
					<string>[~+*%\.]</string>
					<key>name</key>
					<string>support.type</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>comment</key>
					<string>double-quote-string</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>comment</key>
					<string>single-quote-string</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/</string>
					<key>comment</key>
					<string>regex</string>
					<key>end</key>
					<string>/</string>
					<key>name</key>
					<string>string.regexp</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\?</string>
					<key>comment</key>
					<string>special regex</string>
					<key>end</key>
					<string>\?</string>
					<key>name</key>
					<string>string.regexp</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>`</string>
					<key>comment</key>
					<string>special regex</string>
					<key>end</key>
					<string>`</string>
					<key>name</key>
					<string>support.constant</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>non-terminal</string>
					<key>match</key>
					<string>\w(?:\w|[\-_0-9])*\w</string>
					<key>name</key>
					<string>variable.other.tatsu.non-terminal</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.tatsu</string>
	<key>uuid</key>
	<string>D9954069-097B-4361-818D-EF4986D442E7</string>
</dict>
</plist>
