#!/usr/bin/env python3
#
#  CAVEAT UTILITOR
#
#  This file was automatically generated by 竜TatSu v5.20.1
#
#     https://pypi.python.org/pypi/tatsu/
#
#  Any changes you make to it will be overwritten the next time
#  the file is generated.
#
# noqa # type: ignore # ruff: noqa
# copyright: ignore
# fmt: off

from __future__ import annotations

from typing import Any

from tatsu.config import ParserConfig
from tatsu.contexts import CanParse
from tatsu.grammars import *
from tatsu.input import Text
from tatsu.input.buffer import Buffer
from tatsu.input.textlines import TextLines


class TatSuBootstrapParser(CanParse):
    def __init__(self, config: Any = None, **settings: Any):
        self.config = ParserConfig.new(config, **settings)
        self.model = GRAMMAR_MODEL

    def parse(
        self,
        text: str | Text,
        /,
        *,
        start: str | None = None,
        asmodel: bool = True,
        config: Any = None,
        **settings: Any,
    ) -> Any:
        # NOTE:
        #   Copy the grammar so the configuration is unike to this parse
        #   and one parse doesn't leak settings to another.
        #   There may be also configurations that are unique to this parse.
        model = Grammar(
            name=self.model.name,
            rules=self.model.rules,
            directives=self.model.directives,
            keywords=self.model.keywords,
            config=self.config,
        )
        config = ParserConfig.new(config, **settings)
        return model.parse(text, asmodel=asmodel, config=config)


GRAMMAR_MODEL: Grammar = (
    Grammar(
      name='TatSu',
      directives={
        'grammar': 'TatSu',
        'whitespace': '(?m)\\s+',
        'comments': '(?ms)[(][*]\\s*(.*?)\\s*[*][)]|/[*]\\s*(.*?)\\s*[*]/',
        'eol_comments': '(?ms)(?:[#]|[\\/][\\/])(.*?)$',
        'parseinfo': True,
        'left_recursion': False
      },
      keywords=(),
      rules=(
        Rule(
          name='start',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Call('grammar')
        ),
        Rule(
          name='grammar',
          params=['Grammar'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Named(name='title', exp=Constant('TATSU')),
              Closure(
                Choice(
                  [
                    Option(NamedList(name='directives', exp=Call('directive'))),
                    Option(NamedList(name='keywords', exp=Call('keyword')))
                  ]
                )
              ),
              NamedList(name='rules', exp=Call('rule')),
              Closure(
                Choice(
                  [
                    Option(NamedList(name='rules', exp=Call('rule'))),
                    Option(NamedList(name='keywords', exp=Call('keyword')))
                  ]
                )
              ),
              EOF()
            ]
          )
        ),
        Rule(
          name='directive',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Token('@@'),
              NegativeLookahead(Token('keyword')),
              Cut(),
              Group(
                Choice(
                  [
                    Option(
                      Sequence(
                        [
                          Named(
                            name='name',
                            exp=Group(Choice([Option(Token('comments')), Option(Token('eol_comments'))]))
                          ),
                          Cut(),
                          Token('::'),
                          Cut(),
                          Named(name='value', exp=Call('regex'))
                        ]
                      )
                    ),
                    Option(
                      Sequence(
                        [
                          Named(name='name', exp=Token('whitespace')),
                          Cut(),
                          Token('::'),
                          Cut(),
                          Named(
                            name='value',
                            exp=Group(
                              Choice(
                                [
                                  Option(Call('regex')),
                                  Option(Call('string')),
                                  Option(Token('None')),
                                  Option(Token('False')),
                                  Option(Constant())
                                ]
                              )
                            )
                          )
                        ]
                      )
                    ),
                    Option(
                      Sequence(
                        [
                          Named(
                            name='name',
                            exp=Group(
                              Choice(
                                [
                                  Option(Token('nameguard')),
                                  Option(Token('ignorecase')),
                                  Option(Token('left_recursion')),
                                  Option(Token('parseinfo')),
                                  Option(Token('memoization'))
                                ]
                              )
                            )
                          ),
                          Cut(),
                          Group(
                            Choice(
                              [
                                Option(Sequence([Token('::'), Cut(), Named(name='value', exp=Call('boolean'))])),
                                Option(Named(name='value', exp=Constant(True)))
                              ]
                            )
                          )
                        ]
                      )
                    ),
                    Option(
                      Sequence(
                        [
                          Named(name='name', exp=Token('grammar')),
                          Cut(),
                          Token('::'),
                          Cut(),
                          Named(name='value', exp=Call('word'))
                        ]
                      )
                    ),
                    Option(
                      Sequence(
                        [
                          Named(name='name', exp=Token('namechars')),
                          Cut(),
                          Token('::'),
                          Cut(),
                          Named(name='value', exp=Call('string'))
                        ]
                      )
                    )
                  ]
                )
              ),
              Cut()
            ]
          )
        ),
        Rule(
          name='keywords',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=PositiveClosure(Call('keyword'))
        ),
        Rule(
          name='keyword',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Token('@@keyword'),
              Cut(),
              Token('::'),
              PositiveClosure(
                Sequence(
                  [
                    OverrideList(Group(Choice([Option(Call('word')), Option(Call('string'))]))),
                    NegativeLookahead(Group(Choice([Option(Token(':')), Option(Token('='))])))
                  ]
                )
              )
            ]
          )
        ),
        Rule(
          name='params',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              OverrideList(Call('first_param')),
              Closure(
                Sequence(
                  [
                    Token(','),
                    OverrideList(Call('literal')),
                    NegativeLookahead(Token('=')),
                    Cut()
                  ]
                )
              )
            ]
          )
        ),
        Rule(
          name='first_param',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice([Option(Call('path')), Option(Call('literal'))])
        ),
        Rule(
          name='kwparams',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=PositiveGather(exp=Call('pair'), sep=Token(','))
        ),
        Rule(
          name='the_params_at_last',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice(
            [
              Option(Named(name='kwparams', exp=Call('kwparams'))),
              Option(
                Sequence(
                  [
                    Named(name='params', exp=Call('params')),
                    Token(','),
                    Cut(),
                    Named(name='kwparams', exp=Call('kwparams'))
                  ]
                )
              ),
              Option(Named(name='params', exp=Call('params')))
            ]
          )
        ),
        Rule(
          name='paramdef',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice(
            [
              Option(Sequence([Token('['), Cut(), RuleInclude('the_params_at_last'), Token(']')])),
              Option(Sequence([Token('('), Cut(), RuleInclude('the_params_at_last'), Token(')')])),
              Option(Sequence([Token('::'), Cut(), Named(name='params', exp=Call('params'))]))
            ]
          )
        ),
        Rule(
          name='rule',
          params=['Rule'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Named(name='decorators', exp=Closure(Call('decorator'))),
              Named(name='name', exp=Call('name')),
              Cut(),
              Optional(RuleInclude('paramdef')),
              Optional(Sequence([Token('<'), Cut(), Named(name='base', exp=Call('known_name'))])),
              Void(),
              Pattern('=|::=|:=?'),
              Cut(),
              Named(name='exp', exp=Call('expre')),
              Call('ENDRULE'),
              Cut()
            ]
          )
        ),
        Rule(
          name='ENDRULE',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=True,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice(
            [
              Option(Call('DEDENT')),
              Option(Call('BLANK')),
              Option(Token(';')),
              Option(EOF())
            ]
          )
        ),
        Rule(
          name='DEDENT',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=True,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Call('EOL'), Lookahead(Pattern('\\S'))])
        ),
        Rule(
          name='BLANK',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=True,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Call('EOL'), Call('EOL')])
        ),
        Rule(
          name='EOL',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=True,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Pattern('(?m)[ \\t]*$'), Pattern('(?m)(?:\\r?\\n|\\r)?')])
        ),
        Rule(
          name='decorator',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Token('@'),
              NegativeLookahead(Token('@')),
              Cut(),
              Override(Pattern('(override|name|isname|nomemo|nostak)\\b'))
            ]
          )
        ),
        Rule(
          name='pair',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [OverrideList(Call('word')), Token('='), Cut(), OverrideList(Call('literal'))]
          )
        ),
        Rule(
          name='expre',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice([Option(Call('choice')), Option(Call('sequence'))])
        ),
        Rule(
          name='choice',
          params=['Choice'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Optional(Sequence([Token('|'), Cut()])),
              OverrideList(Call('option')),
              PositiveClosure(Sequence([Token('|'), Cut(), OverrideList(Call('option'))]))
            ]
          )
        ),
        Rule(
          name='option',
          params=['Option'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Call('sequence')
        ),
        Rule(
          name='sequence',
          params=['Sequence'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice(
            [
              Option(
                Sequence(
                  [
                    Lookahead(Group(Sequence([Call('element'), Token(',')]))),
                    PositiveGather(exp=Call('element'), sep=Token(','))
                  ]
                )
              ),
              Option(
                PositiveClosure(Sequence([NegativeLookahead(Call('ENDRULE')), Call('element')]))
              )
            ]
          )
        ),
        Rule(
          name='element',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice(
            [
              Option(Call('named')),
              Option(Call('term')),
              Option(Call('override')),
              Option(Call('rule_include'))
            ]
          )
        ),
        Rule(
          name='rule_include',
          params=['RuleInclude'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Token('>'), Cut(), Override(Call('known_name'))])
        ),
        Rule(
          name='named',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice([Option(Call('named_list')), Option(Call('named_single'))])
        ),
        Rule(
          name='named_list',
          params=['NamedList'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Named(name='name', exp=Call('name')),
              Pattern('\\+[:=]'),
              Cut(),
              Named(name='exp', exp=Call('term'))
            ]
          )
        ),
        Rule(
          name='named_single',
          params=['Named'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Named(name='name', exp=Call('name')),
              Pattern('[:=]'),
              Cut(),
              Named(name='exp', exp=Call('term'))
            ]
          )
        ),
        Rule(
          name='override',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice(
            [
              Option(Call('override_list')),
              Option(Call('override_single')),
              Option(Call('override_single_deprecated'))
            ]
          )
        ),
        Rule(
          name='override_list',
          params=['OverrideList'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Pattern('\\+=|@\\+:'), Cut(), Override(Call('term'))])
        ),
        Rule(
          name='override_single',
          params=['Override'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Pattern('=|@:'), Cut(), Override(Call('term'))])
        ),
        Rule(
          name='override_single_deprecated',
          params=['Override'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Token('@'), Cut(), Override(Call('term'))])
        ),
        Rule(
          name='term',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice(
            [
              Option(Call('gather')),
              Option(Call('join')),
              Option(Call('left_join')),
              Option(Call('right_join')),
              Option(Call('empty_closure')),
              Option(Call('positive_closure')),
              Option(Call('closure')),
              Option(Call('optional')),
              Option(Call('atom')),
              Option(Call('void')),
              Option(Call('skip_to')),
              Option(Call('lookahead')),
              Option(Call('negative_lookahead')),
              Option(Call('cut')),
              Option(Call('cut_deprecated'))
            ]
          )
        ),
        Rule(
          name='group',
          params=['Group'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              NegativeLookahead(Token('(?:')),
              Token('('),
              Cut(),
              Override(Call('expre')),
              Token(')'),
              Cut()
            ]
          )
        ),
        Rule(
          name='skip',
          params=['SkipGroup'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Token('(?:'), Cut(), Override(Call('expre')), Token(')'), Cut()])
        ),
        Rule(
          name='gather',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Lookahead(Group(Sequence([Call('atom'), Token('.{')]))),
              Cut(),
              Group(Choice([Option(Call('positive_gather')), Option(Call('normal_gather'))]))
            ]
          )
        ),
        Rule(
          name='positive_gather',
          params=['PositiveGather'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Named(name='sep', exp=Call('atom')),
              Token('.{'),
              Named(name='exp', exp=Call('expre')),
              Token('}'),
              NegativeLookahead(Pattern('\\+=')),
              Pattern('[+-]'),
              Cut()
            ]
          )
        ),
        Rule(
          name='normal_gather',
          params=['Gather'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Named(name='sep', exp=Call('atom')),
              Token('.{'),
              Cut(),
              Named(name='exp', exp=Call('expre')),
              Token('}'),
              Optional(Sequence([Token('*'), Cut()])),
              Cut()
            ]
          )
        ),
        Rule(
          name='join',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Lookahead(Group(Sequence([Call('atom'), Token('%{')]))),
              Cut(),
              Group(Choice([Option(Call('positive_join')), Option(Call('normal_join'))]))
            ]
          )
        ),
        Rule(
          name='positive_join',
          params=['PositiveJoin'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Named(name='sep', exp=Call('atom')),
              Token('%{'),
              Named(name='exp', exp=Call('expre')),
              Token('}'),
              NegativeLookahead(Pattern('\\+=')),
              Pattern('[+-]'),
              Cut()
            ]
          )
        ),
        Rule(
          name='normal_join',
          params=['Join'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Named(name='sep', exp=Call('atom')),
              Token('%{'),
              Cut(),
              Named(name='exp', exp=Call('expre')),
              Token('}'),
              Optional(Sequence([Token('*'), Cut()])),
              Cut()
            ]
          )
        ),
        Rule(
          name='left_join',
          params=['LeftJoin'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Named(name='sep', exp=Call('atom')),
              Token('<{'),
              Cut(),
              Named(name='exp', exp=Call('expre')),
              Token('}'),
              NegativeLookahead(Pattern('\\+=')),
              Pattern('[+-]'),
              Cut()
            ]
          )
        ),
        Rule(
          name='right_join',
          params=['RightJoin'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Named(name='sep', exp=Call('atom')),
              Token('>{'),
              Cut(),
              Named(name='exp', exp=Call('expre')),
              Token('}'),
              NegativeLookahead(Pattern('\\+=')),
              Pattern('[+-]'),
              Cut()
            ]
          )
        ),
        Rule(
          name='positive_closure',
          params=['PositiveClosure'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice(
            [
              Option(
                Sequence(
                  [
                    Token('{'),
                    Override(Call('expre')),
                    Token('}'),
                    NegativeLookahead(Pattern('\\+=')),
                    Pattern('[+-]'),
                    Cut()
                  ]
                )
              ),
              Option(
                Sequence(
                  [
                    Override(Call('atom')),
                    NegativeLookahead(Pattern('\\+=')),
                    Pattern('[+]'),
                    Cut()
                  ]
                )
              )
            ]
          )
        ),
        Rule(
          name='closure',
          params=['Closure'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice(
            [
              Option(
                Sequence(
                  [Token('{'), Override(Call('expre')), Token('}'), Optional(Token('*')), Cut()]
                )
              ),
              Option(Sequence([Override(Call('atom')), Token('*'), Cut()]))
            ]
          )
        ),
        Rule(
          name='empty_closure',
          params=['EmptyClosure'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Token('{}'), Cut(), Override(Void())])
        ),
        Rule(
          name='optional',
          params=['Optional'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice(
            [
              Option(Sequence([Token('['), Cut(), Override(Call('expre')), Token(']'), Cut()])),
              Option(
                Sequence(
                  [
                    Override(Call('atom')),
                    NegativeLookahead(
                      Group(Choice([Option(Token('?"')), Option(Token("?'")), Option(Token('?/'))]))
                    ),
                    Token('?'),
                    Cut()
                  ]
                )
              )
            ]
          )
        ),
        Rule(
          name='lookahead',
          params=['Lookahead'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Token('&'), Cut(), Override(Call('term'))])
        ),
        Rule(
          name='negative_lookahead',
          params=['NegativeLookahead'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Token('!'), Cut(), Override(Call('term'))])
        ),
        Rule(
          name='skip_to',
          params=['SkipTo'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Token('->'), Cut(), Override(Call('term'))])
        ),
        Rule(
          name='atom',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice(
            [
              Option(Call('token')),
              Option(Call('call')),
              Option(Call('dot')),
              Option(Call('pattern')),
              Option(Call('skip')),
              Option(Call('group')),
              Option(Call('eol')),
              Option(Call('eof')),
              Option(Call('alert')),
              Option(Call('constant'))
            ]
          )
        ),
        Rule(
          name='call',
          params=['Call'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Call('word')
        ),
        Rule(
          name='void',
          params=['Void'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Token('()'), Cut()])
        ),
        Rule(
          name='fail',
          params=['Fail'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Token('!()'), Cut()])
        ),
        Rule(
          name='cut',
          params=['Cut'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Token('~'), Cut()])
        ),
        Rule(
          name='cut_deprecated',
          params=['Cut'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Token('>>'), Cut()])
        ),
        Rule(
          name='known_name',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Call('name'), Cut()])
        ),
        Rule(
          name='name',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Call('word')
        ),
        Rule(
          name='constant',
          params=['Constant'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Lookahead(Token('`')),
              Group(
                Choice(
                  [
                    Option(Pattern('(?ms)```((?:.|\\n)*?)```')),
                    Option(Sequence([Token('`'), Override(Call('literal')), Token('`')])),
                    Option(Pattern('`(.*?)`'))
                  ]
                )
              )
            ]
          )
        ),
        Rule(
          name='alert',
          params=['Alert'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Named(name='level', exp=Pattern('\\^+')),
              Named(name='message', exp=Call('constant'))
            ]
          )
        ),
        Rule(
          name='token',
          params=['Token'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice([Option(Call('string')), Option(Call('raw_string'))])
        ),
        Rule(
          name='literal',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice(
            [
              Option(Call('raw_string')),
              Option(Call('value')),
              Option(Call('boolean')),
              Option(Call('none')),
              Option(Call('word')),
              Option(Call('hex')),
              Option(Call('float')),
              Option(Call('int'))
            ]
          )
        ),
        Rule(
          name='string',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Lookahead(Group(Choice([Option(Token('"')), Option(Token("'"))]))),
              Group(
                Choice(
                  [
                    Option(Call('multiline_string')),
                    Option(Call('singlequoted')),
                    Option(Call('doublequoted'))
                  ]
                )
              )
            ]
          )
        ),
        Rule(
          name='singlequoted',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Call('SINGLEQUOTED')
        ),
        Rule(
          name='doublequoted',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Call('DOUBLEQUOTED')
        ),
        Rule(
          name='raw_string',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Lookahead(Pattern('r["\']')), Pattern('r'), Override(Call('STRING'))])
        ),
        Rule(
          name='STRING',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=True,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice([Option(Call('SINGLEQUOTED')), Option(Call('DOUBLEQUOTED'))])
        ),
        Rule(
          name='SINGLEQUOTED',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=True,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Pattern("'((?:[^'\\n]|\\\\'|\\\\\\\\)*?)'"), Cut()])
        ),
        Rule(
          name='DOUBLEQUOTED',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=True,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Pattern('"((?:[^"\\n]|\\\\"|\\\\\\\\)*?)"'), Cut()])
        ),
        Rule(
          name='multiline_string',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice(
            [
              Option(Sequence([Pattern("(?ms)'''((?:\\\\\\\\|\\\\.|.)*?)'''"), Cut()])),
              Option(Sequence([Pattern('(?ms)"""((?:\\\\\\\\|\\\\.|.)*?)"""'), Cut()]))
            ]
          )
        ),
        Rule(
          name='hex',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Pattern('0[xX](?:\\d|[a-fA-F])+')
        ),
        Rule(
          name='float',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Pattern('[-+]?(?:\\d+\\.\\d*|\\d*\\.\\d+)(?:[Ee][-+]?\\d+)?')
        ),
        Rule(
          name='int',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Pattern('[-+]?\\d+')
        ),
        Rule(
          name='path',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Pattern('[_a-zA-Z]\\w*(?:::[_a-zA-Z]\\w*)+')
        ),
        Rule(
          name='word',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Pattern('[_a-zA-Z]\\w*')
        ),
        Rule(
          name='dot',
          params=['Dot'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Token('/./')
        ),
        Rule(
          name='pattern',
          params=['Pattern'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Call('regex')
        ),
        Rule(
          name='regex',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice(
            [
              Option(Call('deprecated_regex')),
              Option(
                Sequence(
                  [
                    NegativeLookahead(Token('?/')),
                    Group(
                      Choice(
                        [
                          Option(Call('REGEX')),
                          Option(Sequence([Token('?'), Override(Call('STRING'))]))
                        ]
                      )
                    )
                  ]
                )
              )
            ]
          )
        ),
        Rule(
          name='REGEX',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=True,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [Lookahead(Token('/')), Pattern('(?ms)/((?:[^/\\\\]|\\\\/|\\\\.)*)/'), Cut()]
          )
        ),
        Rule(
          name='deprecated_regex',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence(
            [
              Token('?/'),
              Cut(),
              Override(Pattern('(?ms)((?:[^/\\\\]|\\\\/|\\\\.)*)')),
              Cut(),
              Token('/?')
            ]
          )
        ),
        Rule(
          name='boolean',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice([Option(Token('True')), Option(Token('False'))])
        ),
        Rule(
          name='none',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Token('None')
        ),
        Rule(
          name='eof',
          params=['EOF'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Sequence([Token('$'), Cut()])
        ),
        Rule(
          name='eol',
          params=['EOL'],
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Token('$->')
        ),
        Rule(
          name='value',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Choice(
            [
              Option(Call('string')),
              Option(Call('number')),
              Option(Call('true')),
              Option(Call('false')),
              Option(Call('null'))
            ]
          )
        ),
        Rule(
          name='number',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Pattern(
            '(?x)\n    -?                                  # Optional negative sign\n    (?:\n        0                               # Can be a lone zero\n        |\n        [1-9][0-9]* # Or a non-zero digit followed by any number of digits\n    )\n    (?: \\. [0-9]+ )?                    # Optional fraction: dot MUST be followed by 1+ digits\n    (?: [eE] [+-]? [0-9]+ )?            # Optional exponent component\n    \\b\n    '
          )
        ),
        Rule(
          name='true',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Token('true')
        ),
        Rule(
          name='false',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Token('false')
        ),
        Rule(
          name='null',
          params=(),
          kwparams={},
          decorators=[],
          is_name=False,
          is_tokn=False,
          no_memo=False,
          no_stak=False,
          is_memo=True,
          is_lrec=False,
          exp=Token('null')
        )
      )
    )
)


class TatSuBootstrapText(TextLines):
    def __init__(
        self,
        text,
        /,
        config: ParserConfig | None = None,
        **settings,
    ) -> None:
        config = ParserConfig.new(
            config=config,
            whitespace=r'(?m)\s+',
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=True,
            comments=r'(?ms)[(][*]\s*(.*?)\s*[*][)]|/[*]\s*(.*?)\s*[*]/',
            eol_comments=r'(?ms)(?:[#]|[\/][\/])(.*?)$',
            keywords=KEYWORDS,
            start='start',
        )
        assert isinstance(config, ParserConfig)
        config = config.override(**settings)

        super().__init__(text, config=config)

TatSuBootstrapTokenizer = TatSuBootstrapText


class TatSuBootstrapBuffer(Buffer):  # NOTE: backwards compatibility
    def __init__(
        self,
        text,
        /,
        config: ParserConfig | None = None,
        **settings,
    ) -> None:
        config = ParserConfig.new(
            config=config,
            whitespace=r'(?m)\s+',
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=True,
            comments=r'(?ms)[(][*]\s*(.*?)\s*[*][)]|/[*]\s*(.*?)\s*[*]/',
            eol_comments=r'(?ms)(?:[#]|[\/][\/])(.*?)$',
            keywords=KEYWORDS,
            start='start',
        )
        assert isinstance(config, ParserConfig)
        config = config.override(**settings)

        super().__init__(text, config=config)


KEYWORDS = ()


def main(filename, **kwargs):
    if not filename or filename == '-':
        import sys

        text = sys.stdin.read()
    else:
        import pathlib

        text = pathlib.Path(filename).read_text()

    parser = TatSuBootstrapParser()
    return parser.parse(text, filename=filename, **kwargs)


if __name__ == '__main__':
    import json
    from tatsu.parsing import generic_main
    from tatsu.util import asjson

    ast = generic_main(main, TatSuBootstrapParser, name='TatSuBootstrap')
    data = asjson(ast)
    print(json.dumps(data, indent=2))
