Grammar(
  name='TatSu',
  directives={
    'grammar': 'TatSu',
    'whitespace': '(?m)\\s+',
    'comments': '(?ms)[(][*]\\s*((?:.|\\n)*?)\\s*[*][)]|[\\/][*]\\s*((?:.|\\n)*?)\\s*[*][\\/]',
    'eol_comments': '(?ms)(?:[#]|[\\/][\\/])(.*?)$',
    'parseinfo': True,
    'left_recursion': False
  },
  keywords=(),
  rules=(
    Rule(
      name='start',
      exp=Call('grammar'),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='grammar',
      exp=Sequence(
        [
          Named(name='title', exp=Constant('TATSU')),
          Closure(
            Choice(
              [
                Option(NamedList(name='directives', exp=Call('directive'))),
                Option(NamedList(name='keywords', exp=Call('keyword')))
              ]
            )
          ),
          NamedList(name='rules', exp=Call('rule')),
          Closure(
            Choice(
              [
                Option(NamedList(name='rules', exp=Call('rule'))),
                Option(NamedList(name='keywords', exp=Call('keyword')))
              ]
            )
          ),
          EOF()
        ]
      ),
      params=['Grammar'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='directive',
      exp=Sequence(
        [
          Token('@@'),
          NegativeLookahead(Token('keyword')),
          Cut(),
          Group(
            Choice(
              [
                Option(
                  Sequence(
                    [
                      Named(
                        name='name',
                        exp=Group(Choice([Option(Token('comments')), Option(Token('eol_comments'))]))
                      ),
                      Cut(),
                      Token('::'),
                      Cut(),
                      Named(name='value', exp=Call('regex'))
                    ]
                  )
                ),
                Option(
                  Sequence(
                    [
                      Named(name='name', exp=Token('whitespace')),
                      Cut(),
                      Token('::'),
                      Cut(),
                      Named(
                        name='value',
                        exp=Group(
                          Choice(
                            [
                              Option(Call('regex')),
                              Option(Call('string')),
                              Option(Token('None')),
                              Option(Token('False')),
                              Option(Constant('None'))
                            ]
                          )
                        )
                      )
                    ]
                  )
                ),
                Option(
                  Sequence(
                    [
                      Named(
                        name='name',
                        exp=Group(
                          Choice(
                            [
                              Option(Token('nameguard')),
                              Option(Token('ignorecase')),
                              Option(Token('left_recursion')),
                              Option(Token('parseinfo')),
                              Option(Token('memoization'))
                            ]
                          )
                        )
                      ),
                      Cut(),
                      Group(
                        Choice(
                          [
                            Option(Sequence([Token('::'), Cut(), Named(name='value', exp=Call('boolean'))])),
                            Option(Named(name='value', exp=Constant(True)))
                          ]
                        )
                      )
                    ]
                  )
                ),
                Option(
                  Sequence(
                    [
                      Named(name='name', exp=Token('grammar')),
                      Cut(),
                      Token('::'),
                      Cut(),
                      Named(name='value', exp=Call('word'))
                    ]
                  )
                ),
                Option(
                  Sequence(
                    [
                      Named(name='name', exp=Token('namechars')),
                      Cut(),
                      Token('::'),
                      Cut(),
                      Named(name='value', exp=Call('string'))
                    ]
                  )
                )
              ]
            )
          ),
          Cut()
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='keywords',
      exp=PositiveClosure(Call('keyword')),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='keyword',
      exp=Sequence(
        [
          Token('@@keyword'),
          Cut(),
          Token('::'),
          PositiveClosure(
            Sequence(
              [
                OverrideList(Group(Choice([Option(Call('word')), Option(Call('string'))]))),
                NegativeLookahead(Group(Choice([Option(Token(':')), Option(Token('='))])))
              ]
            )
          )
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='params',
      exp=Sequence(
        [
          OverrideList(Call('first_param')),
          Closure(
            Sequence(
              [
                Token(','),
                OverrideList(Call('literal')),
                NegativeLookahead(Token('=')),
                Cut()
              ]
            )
          )
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='first_param',
      exp=Choice([Option(Call('path')), Option(Call('literal'))]),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='kwparams',
      exp=PositiveGather(exp=Call('pair'), sep=Token(',')),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='the_params_at_last',
      exp=Choice(
        [
          Option(Named(name='kwparams', exp=Call('kwparams'))),
          Option(
            Sequence(
              [
                Named(name='params', exp=Call('params')),
                Token(','),
                Cut(),
                Named(name='kwparams', exp=Call('kwparams'))
              ]
            )
          ),
          Option(Named(name='params', exp=Call('params')))
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='paramdef',
      exp=Choice(
        [
          Option(Sequence([Token('['), Cut(), RuleInclude('the_params_at_last'), Token(']')])),
          Option(Sequence([Token('('), Cut(), RuleInclude('the_params_at_last'), Token(')')])),
          Option(Sequence([Token('::'), Cut(), Named(name='params', exp=Call('params'))]))
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='rule',
      exp=Sequence(
        [
          Named(name='decorators', exp=Closure(Call('decorator'))),
          Named(name='name', exp=Call('name')),
          Cut(),
          Optional(RuleInclude('paramdef')),
          Optional(Sequence([Token('<'), Cut(), Named(name='base', exp=Call('known_name'))])),
          Void('()'),
          Pattern('=|::=|:=?'),
          Cut(),
          Named(name='exp', exp=Call('expre')),
          Call('ENDRULE'),
          Cut()
        ]
      ),
      params=['Rule'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='ENDRULE',
      exp=Choice(
        [
          Option(Call('DEDENT')),
          Option(Call('BLANK')),
          Option(Token(';')),
          Option(EOF())
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=True,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='DEDENT',
      exp=Sequence([Call('EOL'), Pattern('\\S')]),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=True,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='BLANK',
      exp=Sequence([Call('EOL'), Call('EOL')]),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=True,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='EOL',
      exp=Sequence([Pattern('(?m)[ \\t]*$'), Pattern('(?m)(?:\\r?\\n|\\r)?')]),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=True,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='decorator',
      exp=Sequence(
        [
          Token('@'),
          NegativeLookahead(Token('@')),
          Cut(),
          Override(Pattern('(override|name|isname|nomemo|nostak)\\b'))
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='pair',
      exp=Sequence(
        [OverrideList(Call('word')), Token('='), Cut(), OverrideList(Call('literal'))]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='expre',
      exp=Choice([Option(Call('choice')), Option(Call('sequence'))]),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='choice',
      exp=Sequence(
        [
          Optional(Sequence([Token('|'), Cut()])),
          OverrideList(Call('option')),
          PositiveClosure(Sequence([Token('|'), Cut(), OverrideList(Call('option'))]))
        ]
      ),
      params=['Choice'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='option',
      exp=Call('sequence'),
      params=['Option'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='sequence',
      exp=Choice(
        [
          Option(
            Sequence(
              [
                Lookahead(Group(Sequence([Call('element'), Token(',')]))),
                PositiveGather(exp=Call('element'), sep=Token(','))
              ]
            )
          ),
          Option(
            PositiveClosure(Sequence([NegativeLookahead(Call('ENDRULE')), Call('element')]))
          )
        ]
      ),
      params=['Sequence'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='element',
      exp=Choice(
        [
          Option(Call('named')),
          Option(Call('term')),
          Option(Call('override')),
          Option(Call('rule_include'))
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='rule_include',
      exp=Sequence([Token('>'), Cut(), Override(Call('known_name'))]),
      params=['RuleInclude'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='named',
      exp=Choice([Option(Call('named_list')), Option(Call('named_single'))]),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='named_list',
      exp=Sequence(
        [
          Named(name='name', exp=Call('name')),
          Pattern('\\+[:=]'),
          Cut(),
          Named(name='exp', exp=Call('term'))
        ]
      ),
      params=['NamedList'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='named_single',
      exp=Sequence(
        [
          Named(name='name', exp=Call('name')),
          Pattern('[:=]'),
          Cut(),
          Named(name='exp', exp=Call('term'))
        ]
      ),
      params=['Named'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='override',
      exp=Choice(
        [
          Option(Call('override_list')),
          Option(Call('override_single')),
          Option(Call('override_single_deprecated'))
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='override_list',
      exp=Sequence([Pattern('\\+=|@\\+:'), Cut(), Override(Call('term'))]),
      params=['OverrideList'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='override_single',
      exp=Sequence([Pattern('=|@:'), Cut(), Override(Call('term'))]),
      params=['Override'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='override_single_deprecated',
      exp=Sequence([Token('@'), Cut(), Override(Call('term'))]),
      params=['Override'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='term',
      exp=Choice(
        [
          Option(Call('gather')),
          Option(Call('join')),
          Option(Call('left_join')),
          Option(Call('right_join')),
          Option(Call('empty_closure')),
          Option(Call('positive_closure')),
          Option(Call('closure')),
          Option(Call('optional')),
          Option(Call('atom')),
          Option(Call('void')),
          Option(Call('skip_to')),
          Option(Call('lookahead')),
          Option(Call('negative_lookahead')),
          Option(Call('cut')),
          Option(Call('cut_deprecated'))
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='group',
      exp=Sequence(
        [
          NegativeLookahead(Token('(?:')),
          Token('('),
          Cut(),
          Override(Call('expre')),
          Token(')'),
          Cut()
        ]
      ),
      params=['Group'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='skip',
      exp=Sequence([Token('(?:'), Cut(), Override(Call('expre')), Token(')'), Cut()]),
      params=['SkipGroup'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='gather',
      exp=Sequence(
        [
          Lookahead(Group(Sequence([Call('atom'), Token('.{')]))),
          Cut(),
          Group(Choice([Option(Call('positive_gather')), Option(Call('normal_gather'))]))
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='positive_gather',
      exp=Sequence(
        [
          Named(name='sep', exp=Call('atom')),
          Token('.{'),
          Named(name='exp', exp=Call('expre')),
          Token('}'),
          Pattern('(?!\\+=)[+-]'),
          Cut()
        ]
      ),
      params=['PositiveGather'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='normal_gather',
      exp=Sequence(
        [
          Named(name='sep', exp=Call('atom')),
          Token('.{'),
          Cut(),
          Named(name='exp', exp=Call('expre')),
          Token('}'),
          Optional(Sequence([Token('*'), Cut()])),
          Cut()
        ]
      ),
      params=['Gather'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='join',
      exp=Sequence(
        [
          Lookahead(Group(Sequence([Call('atom'), Token('%{')]))),
          Cut(),
          Group(Choice([Option(Call('positive_join')), Option(Call('normal_join'))]))
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='positive_join',
      exp=Sequence(
        [
          Named(name='sep', exp=Call('atom')),
          Token('%{'),
          Named(name='exp', exp=Call('expre')),
          Token('}'),
          Pattern('(?!\\+=)[+-]'),
          Cut()
        ]
      ),
      params=['PositiveJoin'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='normal_join',
      exp=Sequence(
        [
          Named(name='sep', exp=Call('atom')),
          Token('%{'),
          Cut(),
          Named(name='exp', exp=Call('expre')),
          Token('}'),
          Optional(Sequence([Token('*'), Cut()])),
          Cut()
        ]
      ),
      params=['Join'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='left_join',
      exp=Sequence(
        [
          Named(name='sep', exp=Call('atom')),
          Token('<{'),
          Cut(),
          Named(name='exp', exp=Call('expre')),
          Token('}'),
          Pattern('(?!\\+=)[+-]'),
          Cut()
        ]
      ),
      params=['LeftJoin'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='right_join',
      exp=Sequence(
        [
          Named(name='sep', exp=Call('atom')),
          Token('>{'),
          Cut(),
          Named(name='exp', exp=Call('expre')),
          Token('}'),
          Pattern('(?!\\+=)[+-]'),
          Cut()
        ]
      ),
      params=['RightJoin'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='positive_closure',
      exp=Choice(
        [
          Option(
            Sequence(
              [
                Token('{'),
                Override(Call('expre')),
                Token('}'),
                Pattern('(?!\\+=)[+-]'),
                Cut()
              ]
            )
          ),
          Option(Sequence([Override(Call('atom')), Pattern('(?!\\+=)[+]'), Cut()]))
        ]
      ),
      params=['PositiveClosure'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='closure',
      exp=Choice(
        [
          Option(
            Sequence(
              [Token('{'), Override(Call('expre')), Token('}'), Optional(Token('*')), Cut()]
            )
          ),
          Option(Sequence([Override(Call('atom')), Token('*'), Cut()]))
        ]
      ),
      params=['Closure'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='empty_closure',
      exp=Sequence([Token('{}'), Cut(), Override(Void('()'))]),
      params=['EmptyClosure'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='optional',
      exp=Choice(
        [
          Option(Sequence([Token('['), Cut(), Override(Call('expre')), Token(']'), Cut()])),
          Option(
            Sequence(
              [
                Override(Call('atom')),
                NegativeLookahead(
                  Group(Choice([Option(Token('?"')), Option(Token("?'")), Option(Token('?/'))]))
                ),
                Token('?'),
                Cut()
              ]
            )
          )
        ]
      ),
      params=['Optional'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='lookahead',
      exp=Sequence([Token('&'), Cut(), Override(Call('term'))]),
      params=['Lookahead'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='negative_lookahead',
      exp=Sequence([Token('!'), Cut(), Override(Call('term'))]),
      params=['NegativeLookahead'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='skip_to',
      exp=Sequence([Token('->'), Cut(), Override(Call('term'))]),
      params=['SkipTo'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='atom',
      exp=Choice(
        [
          Option(Call('token')),
          Option(Call('call')),
          Option(Call('dot')),
          Option(Call('pattern')),
          Option(Call('group')),
          Option(Call('eol')),
          Option(Call('eof')),
          Option(Call('skip')),
          Option(Call('alert')),
          Option(Call('constant'))
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='call',
      exp=Call('word'),
      params=['Call'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='void',
      exp=Sequence([Token('()'), Cut()]),
      params=['Void'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='fail',
      exp=Sequence([Token('!()'), Cut()]),
      params=['Fail'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='cut',
      exp=Sequence([Token('~'), Cut()]),
      params=['Cut'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='cut_deprecated',
      exp=Sequence([Token('>>'), Cut()]),
      params=['Cut'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='known_name',
      exp=Sequence([Call('name'), Cut()]),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='name',
      exp=Call('word'),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='constant',
      exp=Sequence(
        [
          Lookahead(Token('`')),
          Group(
            Choice(
              [
                Option(Pattern('(?ms)```((?:.|\\n)*?)```')),
                Option(Sequence([Token('`'), Override(Call('literal')), Token('`')])),
                Option(Pattern('`(.*?)`'))
              ]
            )
          )
        ]
      ),
      params=['Constant'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='alert',
      exp=Sequence(
        [
          Named(name='level', exp=Pattern('\\^+')),
          Named(name='message', exp=Call('constant'))
        ]
      ),
      params=['Alert'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='token',
      exp=Choice([Option(Call('string')), Option(Call('raw_string'))]),
      params=['Token'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='literal',
      exp=Choice(
        [
          Option(Call('string')),
          Option(Call('raw_string')),
          Option(Call('boolean')),
          Option(Call('word')),
          Option(Call('hex')),
          Option(Call('float')),
          Option(Call('int')),
          Option(Call('null'))
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='string',
      exp=Sequence(
        [
          Lookahead(Group(Choice([Option(Token('"')), Option(Token("'"))]))),
          Group(
            Choice(
              [
                Option(Call('multiline_string')),
                Option(Call('singlequoted')),
                Option(Call('doublequoted'))
              ]
            )
          )
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='singlequoted',
      exp=Call('SINGLEQUOTED'),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='doublequoted',
      exp=Call('DOUBLEQUOTED'),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='raw_string',
      exp=Sequence([Pattern('r(?=["\'])'), Override(Call('STRING'))]),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='STRING',
      exp=Choice([Option(Call('SINGLEQUOTED')), Option(Call('DOUBLEQUOTED'))]),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=True,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='SINGLEQUOTED',
      exp=Sequence([Pattern("'((?:[^'\\n]|\\\\'|\\\\\\\\)*?)'"), Cut()]),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=True,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='DOUBLEQUOTED',
      exp=Sequence([Pattern('"((?:[^"\\n]|\\\\"|\\\\\\\\)*?)"'), Cut()]),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=True,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='multiline_string',
      exp=Choice(
        [
          Option(Sequence([Pattern("(?ms)'''((?:\\\\\\\\|\\\\.|(?!''').)*?)'''"), Cut()])),
          Option(Sequence([Pattern('(?ms)"""((?:\\\\\\\\|\\\\.|(?!""").)*?)"""'), Cut()]))
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='hex',
      exp=Pattern('0[xX](?:\\d|[a-fA-F])+'),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='float',
      exp=Pattern('[-+]?(?:\\d+\\.\\d*|\\d*\\.\\d+)(?:[Ee][-+]?\\d+)?'),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='int',
      exp=Pattern('[-+]?\\d+'),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='path',
      exp=Pattern('(?!\\d)\\w+(?:::(?!\\d)\\w+)+'),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='word',
      exp=Pattern('(?!\\d)\\w+'),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='dot',
      exp=Token('/./'),
      params=['Dot'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='pattern',
      exp=Call('regex'),
      params=['Pattern'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='regex',
      exp=Choice(
        [
          Option(Call('deprecated_regex')),
          Option(
            Sequence(
              [
                NegativeLookahead(Token('?/')),
                Group(
                  Choice(
                    [
                      Option(Call('REGEX')),
                      Option(Sequence([Token('?'), Override(Call('STRING'))]))
                    ]
                  )
                )
              ]
            )
          )
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='REGEX',
      exp=Sequence(
        [Lookahead(Token('/')), Pattern('(?ms)/((?:[^/\\\\]|\\\\/|\\\\.)*)/'), Cut()]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=True,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='deprecated_regex',
      exp=Sequence(
        [
          Token('?/'),
          Cut(),
          Override(Pattern('(?ms)((?:[^/\\\\]|\\\\/|\\\\.)*)')),
          Cut(),
          Token('/?')
        ]
      ),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='boolean',
      exp=Choice([Option(Token('True')), Option(Token('False'))]),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='null',
      exp=Token('None'),
      params=(),
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='eof',
      exp=Sequence([Token('$'), Cut()]),
      params=['EOF'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    ),
    Rule(
      name='eol',
      exp=Token('$->'),
      params=['EOL'],
      kwparams={},
      decorators=[],
      is_name=False,
      is_tokn=False,
      no_memo=False,
      no_stak=False,
      is_memo=True,
      is_lrec=False
    )
  )
)