#!/usr/bin/env python3

# CAVEAT UTILITOR
#
#  This file was automatically generated by 竜TatSu.
#
#     https://pypi.python.org/pypi/tatsu/
#
#  Any changes you make to it will be overwritten the next time
#  the file is generated.

# ruff: noqa: RUF100, C405, COM812, I001, F401, PLR1702, PLC2801, SIM117
# ruff: noqa: PL2401, PLC2402, PLC2403, E303
# fmt: off

from __future__ import annotations

from tatsu.buffering import Buffer
from tatsu.infos import ParserConfig
from tatsu.parsing import Parser, generic_main, rule
from tatsu.tokenizing.textlines import TextLinesTokenizer

__all__ = ['TatSuBootstrapTokenizer', 'TatSuBootstrapParser', 'main']


KEYWORDS: set[str] = set()


class TatSuBootstrapTokenizer(TextLinesTokenizer):
    def __init__(self, text, /, config: ParserConfig | None = None, **settings):
        config = ParserConfig.new(
            config,
            whitespace=r'(?m)\s+',
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=True,
            comments=r'(?ms)[(][*]\s*((?:.|\n)*?)\s*[*][)]|[\/][*]\s*((?:.|\n)*?)\s*[*][\/]',
            eol_comments=r'(?ms)(?:[#]|[\/][\/])(.*?)$',
            keywords=KEYWORDS,
            start='start',
        )
        config = config.override(**settings)

        super().__init__(text, config=config)


class TatSuBootstrapBuffer(Buffer):  # NOTE: backwards compatibility
    def __init__(self, text, /, config: ParserConfig | None = None, **settings):
        config = ParserConfig.new(
            config,
            whitespace=r'(?m)\s+',
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=True,
            comments=r'(?ms)[(][*]\s*((?:.|\n)*?)\s*[*][)]|[\/][*]\s*((?:.|\n)*?)\s*[*][\/]',
            eol_comments=r'(?ms)(?:[#]|[\/][\/])(.*?)$',
            keywords=KEYWORDS,
            start='start',
        )
        config = config.override(**settings)

        super().__init__(text, config=config)


class TatSuBootstrapParser(Parser):
    def __init__(self, /, config: ParserConfig | None = None, **settings):
        config = ParserConfig.new(
            config,
            whitespace=r'(?m)\s+',
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=True,
            comments=r'(?ms)[(][*]\s*((?:.|\n)*?)\s*[*][)]|[\/][*]\s*((?:.|\n)*?)\s*[*][\/]',
            eol_comments=r'(?ms)(?:[#]|[\/][\/])(.*?)$',
            keywords=KEYWORDS,
            start='start',
        )
        config = config.override(**settings)

        super().__init__(
            config=config,
            tokenizercls=config.tokenizercls or TatSuBootstrapTokenizer,
        )

    @rule()
    def _start_(self):
        self._grammar_()

    @rule('Grammar')
    def _grammar_(self):
        with self._setname('title'):
            self._constant('TATSU')

        def block0():
            with self._choice() as choice:
                @choice.option
                def _():
                    with self._addname('directives'):
                        self._directive_()

                @choice.option
                def _():
                    with self._addname('keywords'):
                        self._keyword_()

                choice.expecting('<directive>', '<keyword>')

        self._closure(block0)
        with self._addname('rules'):
            self._rule_()

        def block1():
            with self._choice() as choice:
                @choice.option
                def _():
                    with self._addname('rules'):
                        self._rule_()

                @choice.option
                def _():
                    with self._addname('keywords'):
                        self._keyword_()

                choice.expecting('<rule>', '<keyword>')

        self._closure(block1)
        self._check_eof()
        self._define(['title'], ['directives', 'keywords', 'rules'])

    @rule()
    def _directive_(self):
        self._token('@@')
        with self._ifnot():
            self._token('keyword')
        self._cut()
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    with self._setname('name'):
                        with self._group():
                            with self._choice() as choice:
                                @choice.option
                                def _():
                                    self._token('comments')

                                @choice.option
                                def _():
                                    self._token('eol_comments')

                                choice.expecting('comments', 'eol_comments')
                    self._cut()
                    self._token('::')
                    self._cut()
                    with self._setname('value'):
                        self._regex_()
                    self._define(['name', 'value'], [])

                @choice.option
                def _():
                    with self._setname('name'):
                        with self._group():
                            self._token('whitespace')
                    self._cut()
                    self._token('::')
                    self._cut()
                    with self._setname('value'):
                        with self._group():
                            with self._choice() as choice:
                                @choice.option
                                def _():
                                    self._regex_()

                                @choice.option
                                def _():
                                    self._string_()

                                @choice.option
                                def _():
                                    self._token('None')

                                @choice.option
                                def _():
                                    self._token('False')

                                @choice.option
                                def _():
                                    self._constant('None')

                                choice.expecting(
                                    'None',
                                    '<string>',
                                    'False',
                                    '<regex>'
                                )

                    self._define(['name', 'value'], [])

                @choice.option
                def _():
                    with self._setname('name'):
                        with self._group():
                            with self._choice() as choice:
                                @choice.option
                                def _():
                                    self._token('nameguard')

                                @choice.option
                                def _():
                                    self._token('ignorecase')

                                @choice.option
                                def _():
                                    self._token('left_recursion')

                                @choice.option
                                def _():
                                    self._token('parseinfo')

                                @choice.option
                                def _():
                                    self._token('memoization')

                                choice.expecting(
                                    'ignorecase',
                                    'left_recursion',
                                    'memoization',
                                    'nameguard',
                                    'parseinfo'
                                )

                    self._cut()
                    with self._group():
                        with self._choice() as choice:
                            @choice.option
                            def _():
                                self._token('::')
                                self._cut()
                                with self._setname('value'):
                                    self._boolean_()
                                self._define(['value'], [])

                            @choice.option
                            def _():
                                with self._setname('value'):
                                    self._constant(True)

                            choice.expecting('::')
                    self._define(['name', 'value'], [])

                @choice.option
                def _():
                    with self._setname('name'):
                        with self._group():
                            self._token('grammar')
                    self._cut()
                    self._token('::')
                    self._cut()
                    with self._setname('value'):
                        self._word_()
                    self._define(['name', 'value'], [])

                @choice.option
                def _():
                    with self._setname('name'):
                        with self._group():
                            self._token('namechars')
                    self._cut()
                    self._token('::')
                    self._cut()
                    with self._setname('value'):
                        self._string_()
                    self._define(['name', 'value'], [])

                choice.expecting(
                    'namechars',
                    'whitespace',
                    'eol_comments',
                    'ignorecase',
                    'comments',
                    'left_recursion',
                    'memoization',
                    'nameguard',
                    'parseinfo',
                    'grammar'
                )

        self._cut()
        self._define(['name', 'value'], [])

    @rule()
    def _keywords_(self):

        def block0():
            self._keywords_()

        self._positive_closure(block0)

    @rule()
    def _keyword_(self):
        self._token('@@keyword')
        self._cut()
        self._token('::')
        self._cut()

        def block0():
            with self._addname('@'):
                with self._group():
                    with self._choice() as choice:
                        @choice.option
                        def _():
                            self._word_()

                        @choice.option
                        def _():
                            self._string_()

                        choice.expecting('<word>', '<string>')
            with self._ifnot():
                with self._group():
                    with self._choice() as choice:
                        @choice.option
                        def _():
                            self._token(':')

                        @choice.option
                        def _():
                            self._token('=')

                        choice.expecting(':', '=')

        self._closure(block0)

    @rule()
    def _the_params_at_last_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                with self._setname('kwparams'):
                    self._kwparams_()

            @choice.option
            def _():
                with self._setname('params'):
                    self._params_()
                self._token(',')
                self._cut()
                with self._setname('kwparams'):
                    self._kwparams_()
                self._define(['kwparams', 'params'], [])

            @choice.option
            def _():
                with self._setname('params'):
                    self._params_()

            choice.expecting('<kwparams>', '<params>')

    @rule()
    def _paramdef_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                self._token('[')
                self._cut()
                with self._choice() as choice:
                    @choice.option
                    def _():
                        with self._setname('kwparams'):
                            self._kwparams_()

                    @choice.option
                    def _():
                        with self._setname('params'):
                            self._params_()
                        self._token(',')
                        self._cut()
                        with self._setname('kwparams'):
                            self._kwparams_()
                        self._define(['kwparams', 'params'], [])

                    @choice.option
                    def _():
                        with self._setname('params'):
                            self._params_()

                    choice.expecting('<kwparams>', '<params>')
                self._token(']')
                self._define(['kwparams', 'params'], [])

            @choice.option
            def _():
                self._token('(')
                self._cut()
                with self._choice() as choice:
                    @choice.option
                    def _():
                        with self._setname('kwparams'):
                            self._kwparams_()

                    @choice.option
                    def _():
                        with self._setname('params'):
                            self._params_()
                        self._token(',')
                        self._cut()
                        with self._setname('kwparams'):
                            self._kwparams_()
                        self._define(['kwparams', 'params'], [])

                    @choice.option
                    def _():
                        with self._setname('params'):
                            self._params_()

                    choice.expecting('<kwparams>', '<params>')
                self._token(')')
                self._define(['kwparams', 'params'], [])

            @choice.option
            def _():
                self._token('::')
                self._cut()
                with self._setname('params'):
                    self._params_()
                self._define(['params'], [])

            choice.expecting('[', '::', '(')

    @rule('Rule')
    def _rule_(self):
        with self._setname('decorators'):

            def block0():
                self._decorator_()

            self._closure(block0)
        with self._setname('name'):
            self._name_()
        self._cut()
        with self._optional():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._token('[')
                    self._cut()
                    with self._choice() as choice:
                        @choice.option
                        def _():
                            with self._setname('kwparams'):
                                self._kwparams_()

                        @choice.option
                        def _():
                            with self._setname('params'):
                                self._params_()
                            self._token(',')
                            self._cut()
                            with self._setname('kwparams'):
                                self._kwparams_()
                            self._define(['kwparams', 'params'], [])

                        @choice.option
                        def _():
                            with self._setname('params'):
                                self._params_()

                        choice.expecting('<kwparams>', '<params>')
                    self._token(']')
                    self._define(['kwparams', 'params'], [])

                @choice.option
                def _():
                    self._token('(')
                    self._cut()
                    with self._choice() as choice:
                        @choice.option
                        def _():
                            with self._setname('kwparams'):
                                self._kwparams_()

                        @choice.option
                        def _():
                            with self._setname('params'):
                                self._params_()
                            self._token(',')
                            self._cut()
                            with self._setname('kwparams'):
                                self._kwparams_()
                            self._define(['kwparams', 'params'], [])

                        @choice.option
                        def _():
                            with self._setname('params'):
                                self._params_()

                        choice.expecting('<kwparams>', '<params>')
                    self._token(')')
                    self._define(['kwparams', 'params'], [])

                @choice.option
                def _():
                    self._token('::')
                    self._cut()
                    with self._setname('params'):
                        self._params_()
                    self._define(['params'], [])

                choice.expecting('[', '::', '(')
        with self._optional():
            self._token('<')
            self._cut()
            with self._setname('base'):
                self._known_name_()
            self._define(['base'], [])
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._token('=')

                @choice.option
                def _():
                    self._token(':=')

                @choice.option
                def _():
                    self._token(':')

                choice.expecting(':', ':=', '=')
        self._cut()
        with self._setname('exp'):
            self._expre_()
        self._ENDRULE_()
        self._cut()
        self._define(['base', 'decorators', 'exp', 'kwparams', 'name', 'params'], [])

    @rule()
    def _ENDRULE_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                with self._if():
                    self._UNINDENTED_()

            @choice.option
            def _():
                self._EMPTYLINE_()
                with self._optional():
                    self._token(';')

            @choice.option
            def _():
                self._check_eof()

            @choice.option
            def _():
                self._token(';')

            choice.expecting(
                '<EMPTYLINE>',
                ';',
                '<UNINDENTED>',
                '(?=\\s*(?:\\r?\\n|\\r)[^\\s])',
                '(?:\\s*(?:\\r?\\n|\\r)){2,}'
            )


    @rule()
    def _UNINDENTED_(self):
        self._pattern(r'(?=\s*(?:\r?\n|\r)[^\s])')

    @rule()
    def _EMPTYLINE_(self):
        self._pattern(r'(?:\s*(?:\r?\n|\r)){2,}')

    @rule()
    def _decorator_(self):
        self._token('@')
        with self._ifnot():
            self._token('@')
        self._cut()
        with self._setname('@'):
            with self._group():
                with self._choice() as choice:
                    @choice.option
                    def _():
                        self._token('override')

                    @choice.option
                    def _():
                        self._token('name')

                    @choice.option
                    def _():
                        self._token('nomemo')

                    choice.expecting('override', 'name', 'nomemo')

    @rule()
    def _params_(self):
        with self._addname('@'):
            self._first_param_()

        def block0():
            self._token(',')
            with self._addname('@'):
                self._literal_()
            with self._ifnot():
                self._token('=')
            self._cut()

        self._closure(block0)

    @rule()
    def _first_param_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                self._path_()

            @choice.option
            def _():
                self._literal_()

            choice.expecting(
                '<word>',
                '(?!\\d)\\w+(?:::(?!\\d)\\w+)+',
                '<null>',
                '<path>',
                '<literal>',
                '<boolean>',
                '<raw_string>',
                '<int>',
                '<string>',
                '<hex>',
                '<float>'
            )


    @rule()
    def _kwparams_(self):

        def sep0():
            self._token(',')

        def block1():
            self._pair_()

        self._positive_gather(block1, sep0)

    @rule()
    def _pair_(self):
        with self._addname('@'):
            self._word_()
        self._token('=')
        self._cut()
        with self._addname('@'):
            self._literal_()

    @rule()
    def _expre_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                self._choice_()

            @choice.option
            def _():
                self._sequence_()

            choice.expecting(
                '<choice>',
                '<sequence>',
                '<ENDRULE>',
                '|',
                '<element>',
                '<EMPTYLINE>',
                ';',
                '<UNINDENTED>',
                '<option>'
            )


    @rule('Choice')
    def _choice_(self):
        with self._optional():
            self._token('|')
            self._cut()
        with self._addname('@'):
            self._option_()

        def block0():
            self._token('|')
            self._cut()
            with self._addname('@'):
                self._option_()

        self._positive_closure(block0)

    @rule('Option')
    def _option_(self):
        with self._setname('@'):
            self._sequence_()

    @rule('Sequence')
    def _sequence_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                with self._if():
                    with self._group():
                        self._element_()
                        self._token(',')

                def sep0():
                    self._token(',')

                def block1():
                    self._element_()

                self._positive_gather(block1, sep0)

            @choice.option
            def _():

                def block2():
                    with self._ifnot():
                        self._ENDRULE_()
                    self._element_()

                self._positive_closure(block2)

            choice.expecting(
                '<named>',
                '<ENDRULE>',
                '<term>',
                '<rule_include>',
                '<element>',
                '<EMPTYLINE>',
                ';',
                '<override>',
                '<UNINDENTED>',
                '(?=\\s*(?:\\r?\\n|\\r)[^\\s])',
                '(?:\\s*(?:\\r?\\n|\\r)){2,}'
            )


    @rule()
    def _element_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                self._rule_include_()

            @choice.option
            def _():
                self._named_()

            @choice.option
            def _():
                self._override_()

            @choice.option
            def _():
                self._term_()

            choice.expecting(
                '<left_join>',
                '<cut>',
                '<override_single>',
                '<rule_include>',
                '<named_list>',
                '<named_single>',
                '<join>',
                '<gather>',
                '<closure>',
                '<cut_deprecated>',
                '<negative_lookahead>',
                '<lookahead>',
                '<override>',
                '<named>',
                '<optional>',
                '<skip_to>',
                '<empty_closure>',
                '<override_list>',
                '<term>',
                '<void>',
                '<override_single_deprecated>',
                '<right_join>',
                '<atom>',
                '>',
                '<positive_closure>'
            )


    @rule('RuleInclude')
    def _rule_include_(self):
        self._token('>')
        self._cut()
        with self._setname('@'):
            self._known_name_()

    @rule()
    def _named_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                self._named_list_()

            @choice.option
            def _():
                self._named_single_()

            choice.expecting('<named_single>', '<named_list>', '<name>')

    @rule('NamedList')
    def _named_list_(self):
        with self._setname('name'):
            self._name_()
        self._token('+:')
        self._cut()
        with self._setname('exp'):
            self._term_()
        self._define(['exp', 'name'], [])

    @rule('Named')
    def _named_single_(self):
        with self._setname('name'):
            self._name_()
        self._token(':')
        self._cut()
        with self._setname('exp'):
            self._term_()
        self._define(['exp', 'name'], [])

    @rule()
    def _override_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                self._override_list_()

            @choice.option
            def _():
                self._override_single_()

            @choice.option
            def _():
                self._override_single_deprecated_()

            choice.expecting(
                '@:',
                '<override_single>',
                '@',
                '<override_list>',
                '@+:',
                '<override_single_deprecated>'
            )


    @rule('OverrideList')
    def _override_list_(self):
        self._token('@+:')
        self._cut()
        with self._setname('@'):
            self._term_()

    @rule('Override')
    def _override_single_(self):
        self._token('@:')
        self._cut()
        with self._setname('@'):
            self._term_()

    @rule('Override')
    def _override_single_deprecated_(self):
        self._token('@')
        self._cut()
        with self._setname('@'):
            self._term_()

    @rule()
    def _term_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                self._void_()

            @choice.option
            def _():
                self._gather_()

            @choice.option
            def _():
                self._join_()

            @choice.option
            def _():
                self._left_join_()

            @choice.option
            def _():
                self._right_join_()

            @choice.option
            def _():
                self._empty_closure_()

            @choice.option
            def _():
                self._positive_closure_()

            @choice.option
            def _():
                self._closure_()

            @choice.option
            def _():
                self._optional_()

            @choice.option
            def _():
                self._skip_to_()

            @choice.option
            def _():
                self._lookahead_()

            @choice.option
            def _():
                self._negative_lookahead_()

            @choice.option
            def _():
                self._cut_()

            @choice.option
            def _():
                self._cut_deprecated_()

            @choice.option
            def _():
                self._atom_()

            choice.expecting(
                '<left_join>',
                '<cut>',
                '<join>',
                '<gather>',
                '{}',
                '<closure>',
                '<cut_deprecated>',
                '&',
                '>>',
                '<negative_lookahead>',
                '<group>',
                '<alert>',
                '<eof>',
                '<lookahead>',
                '->',
                '{',
                '<optional>',
                '(',
                '<skip_to>',
                '<empty_closure>',
                '!',
                '<void>',
                '<dot>',
                '<token>',
                '<pattern>',
                '<right_join>',
                '<call>',
                '~',
                '<atom>',
                '<constant>',
                '<positive_closure>',
                '()',
                '['
            )


    @rule('Group')
    def _group_(self):
        self._token('(')
        self._cut()
        with self._setname('@'):
            self._expre_()
        self._token(')')
        self._cut()

    @rule()
    def _gather_(self):
        with self._if():
            with self._group():
                self._atom_()
                self._token('.{')
        self._cut()
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._positive_gather_()

                @choice.option
                def _():
                    self._normal_gather_()

                choice.expecting('<normal_gather>', '<positive_gather>')

    @rule('PositiveGather')
    def _positive_gather_(self):
        with self._setname('sep'):
            self._atom_()
        self._token('.{')
        with self._setname('exp'):
            self._expre_()
        self._token('}')
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._token('+')

                @choice.option
                def _():
                    self._token('-')

                choice.expecting('-', '+')
        self._cut()
        self._define(['exp', 'sep'], [])

    @rule('Gather')
    def _normal_gather_(self):
        with self._setname('sep'):
            self._atom_()
        self._token('.{')
        self._cut()
        with self._setname('exp'):
            self._expre_()
        self._token('}')
        with self._optional():
            self._token('*')
            self._cut()
        self._cut()
        self._define(['exp', 'sep'], [])

    @rule()
    def _join_(self):
        with self._if():
            with self._group():
                self._atom_()
                self._token('%{')
        self._cut()
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._positive_join_()

                @choice.option
                def _():
                    self._normal_join_()

                choice.expecting('<normal_join>', '<positive_join>')

    @rule('PositiveJoin')
    def _positive_join_(self):
        with self._setname('sep'):
            self._atom_()
        self._token('%{')
        with self._setname('exp'):
            self._expre_()
        self._token('}')
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._token('+')

                @choice.option
                def _():
                    self._token('-')

                choice.expecting('-', '+')
        self._cut()
        self._define(['exp', 'sep'], [])

    @rule('Join')
    def _normal_join_(self):
        with self._setname('sep'):
            self._atom_()
        self._token('%{')
        self._cut()
        with self._setname('exp'):
            self._expre_()
        self._token('}')
        with self._optional():
            self._token('*')
            self._cut()
        self._cut()
        self._define(['exp', 'sep'], [])

    @rule('LeftJoin')
    def _left_join_(self):
        with self._setname('sep'):
            self._atom_()
        self._token('<{')
        self._cut()
        with self._setname('exp'):
            self._expre_()
        self._token('}')
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._token('+')

                @choice.option
                def _():
                    self._token('-')

                choice.expecting('-', '+')
        self._cut()
        self._define(['exp', 'sep'], [])

    @rule('RightJoin')
    def _right_join_(self):
        with self._setname('sep'):
            self._atom_()
        self._token('>{')
        self._cut()
        with self._setname('exp'):
            self._expre_()
        self._token('}')
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._token('+')

                @choice.option
                def _():
                    self._token('-')

                choice.expecting('-', '+')
        self._cut()
        self._define(['exp', 'sep'], [])

    @rule('PositiveClosure')
    def _positive_closure_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                self._token('{')
                with self._setname('@'):
                    self._expre_()
                self._token('}')
                with self._group():
                    with self._choice() as choice:
                        @choice.option
                        def _():
                            self._token('-')

                        @choice.option
                        def _():
                            self._token('+')

                        choice.expecting('-', '+')
                self._cut()

            @choice.option
            def _():
                with self._setname('@'):
                    self._atom_()
                self._token('+')
                self._cut()

            choice.expecting(
                '<group>',
                '<atom>',
                '<alert>',
                '<eof>',
                '{',
                '<dot>',
                '<token>',
                '<constant>',
                '<pattern>',
                '<call>',
                '('
            )


    @rule('Closure')
    def _closure_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                self._token('{')
                with self._setname('@'):
                    self._expre_()
                self._token('}')
                with self._optional():
                    self._token('*')
                self._cut()

            @choice.option
            def _():
                with self._setname('@'):
                    self._atom_()
                self._token('*')
                self._cut()

            choice.expecting(
                '<group>',
                '<atom>',
                '<alert>',
                '<eof>',
                '{',
                '<dot>',
                '<token>',
                '<constant>',
                '<pattern>',
                '<call>',
                '('
            )


    @rule('EmptyClosure')
    def _empty_closure_(self):
        self._token('{}')
        self._cut()
        with self._setname('@'):
            self._void()

    @rule('Optional')
    def _optional_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                self._token('[')
                self._cut()
                with self._setname('@'):
                    self._expre_()
                self._token(']')
                self._cut()

            @choice.option
            def _():
                with self._setname('@'):
                    self._atom_()
                with self._ifnot():
                    with self._group():
                        with self._choice() as choice:
                            @choice.option
                            def _():
                                self._token('?"')

                            @choice.option
                            def _():
                                self._token("?'")

                            @choice.option
                            def _():
                                self._token('?/')

                            choice.expecting('?"', '?/', "?'")
                self._token('?')
                self._cut()

            choice.expecting(
                '<group>',
                '<atom>',
                '<alert>',
                '<eof>',
                '<dot>',
                '<token>',
                '<constant>',
                '<pattern>',
                '[',
                '<call>',
                '('
            )


    @rule('Lookahead')
    def _lookahead_(self):
        self._token('&')
        self._cut()
        with self._setname('@'):
            self._term_()

    @rule('NegativeLookahead')
    def _negative_lookahead_(self):
        self._token('!')
        self._cut()
        with self._setname('@'):
            self._term_()

    @rule('SkipTo')
    def _skip_to_(self):
        self._token('->')
        self._cut()
        with self._setname('@'):
            self._term_()

    @rule()
    def _atom_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                self._group_()

            @choice.option
            def _():
                self._token_()

            @choice.option
            def _():
                self._alert_()

            @choice.option
            def _():
                self._constant_()

            @choice.option
            def _():
                self._call_()

            @choice.option
            def _():
                self._pattern_()

            @choice.option
            def _():
                self._dot_()

            @choice.option
            def _():
                self._eof_()

            choice.expecting(
                '<word>',
                '<group>',
                '/./',
                '<alert>',
                '<regexes>',
                '<eof>',
                '$',
                '<raw_string>',
                '<dot>',
                '<token>',
                '`',
                '<constant>',
                '<string>',
                '<pattern>',
                '\\^+',
                '<call>',
                '('
            )


    @rule('Call')
    def _call_(self):
        self._word_()

    @rule('Void')
    def _void_(self):
        self._token('()')
        self._cut()

    @rule('Fail')
    def _fail_(self):
        self._token('!()')
        self._cut()

    @rule('Cut')
    def _cut_(self):
        self._token('~')
        self._cut()

    @rule('Cut')
    def _cut_deprecated_(self):
        self._token('>>')
        self._cut()

    @rule()
    def _known_name_(self):
        self._name_()
        self._cut()

    @rule()
    def _name_(self):
        self._word_()

    @rule('Constant')
    def _constant_(self):
        with self._if():
            self._token('`')
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._pattern(r'(?ms)```((?:.|\n)*?)```')

                @choice.option
                def _():
                    self._token('`')
                    with self._setname('@'):
                        self._literal_()
                    self._token('`')

                @choice.option
                def _():
                    self._pattern(r'`(.*?)`')

                choice.expecting('`', '`(.*?)`', '(?ms)```((?:.|\\n)*?)```')

    @rule('Alert')
    def _alert_(self):
        with self._setname('level'):
            self._pattern(r'\^+')
        with self._setname('message'):
            self._constant_()
        self._define(['level', 'message'], [])

    @rule('Token')
    def _token_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                self._string_()

            @choice.option
            def _():
                self._raw_string_()

            choice.expecting('<raw_string>', '<string>', '<STRING>', 'r')

    @rule()
    def _literal_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                self._string_()

            @choice.option
            def _():
                self._raw_string_()

            @choice.option
            def _():
                self._boolean_()

            @choice.option
            def _():
                self._word_()

            @choice.option
            def _():
                self._hex_()

            @choice.option
            def _():
                self._float_()

            @choice.option
            def _():
                self._int_()

            @choice.option
            def _():
                self._null_()

            choice.expecting(
                '<word>',
                '<null>',
                '[-+]?\\d+',
                'None',
                '<boolean>',
                '<raw_string>',
                '[-+]?(?:\\d+\\.\\d*|\\d*\\.\\d+)(?:[Ee][-+]?\\d+)?',
                '<int>',
                '(?!\\d)\\w+',
                '0[xX](?:\\d|[a-fA-F])+',
                '<string>',
                'False',
                'r',
                '<hex>',
                'True',
                '<STRING>',
                '<float>'
            )


    @rule()
    def _string_(self):
        self._STRING_()

    @rule()
    def _raw_string_(self):
        self._pattern(r'r')
        with self._setname('@'):
            self._STRING_()

    @rule()
    def _STRING_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                with self._setname('@'):
                    self._pattern(r'"((?:[^"\n]|\\"|\\\\)*?)"')
                self._cut()

            @choice.option
            def _():
                with self._setname('@'):
                    self._pattern(r"'((?:[^'\n]|\\'|\\\\)*?)'")
                self._cut()

            choice.expecting(
                '"((?:[^"\\n]|\\\\"|\\\\\\\\)*?)"',
                "'((?:[^'\\n]|\\\\'|\\\\\\\\)*?)'"
            )


    @rule()
    def _hex_(self):
        self._pattern(r'0[xX](?:\d|[a-fA-F])+')

    @rule()
    def _float_(self):
        self._pattern(r'[-+]?(?:\d+\.\d*|\d*\.\d+)(?:[Ee][-+]?\d+)?')

    @rule()
    def _int_(self):
        self._pattern(r'[-+]?\d+')

    @rule()
    def _path_(self):
        self._pattern(r'(?!\d)\w+(?:::(?!\d)\w+)+')

    @rule()
    def _word_(self):
        self._pattern(r'(?!\d)\w+')

    @rule('Dot')
    def _dot_(self):
        self._token('/./')

    @rule('Pattern')
    def _pattern_(self):
        self._regexes_()

    @rule()
    def _regexes_(self):

        def sep0():
            self._token('+')

        def block1():
            self._regex_()

        self._positive_gather(block1, sep0)

    @rule()
    def _regex_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                self._token('/')
                self._cut()
                with self._setname('@'):
                    self._pattern(r'(?:[^/\\]|\\/|\\.)*')
                self._token('/')
                self._cut()

            @choice.option
            def _():
                self._token('?')
                with self._setname('@'):
                    self._STRING_()

            @choice.option
            def _():
                self._deprecated_regex_()

            choice.expecting('?', '/', '<deprecated_regex>', '?/')

    @rule()
    def _deprecated_regex_(self):
        self._token('?/')
        self._cut()
        with self._setname('@'):
            self._pattern(r'(?:.|\n)*?(?=/\?)')
        self._pattern(r'/\?+')
        self._cut()

    @rule()
    def _boolean_(self):
        with self._choice() as choice:
            @choice.option
            def _():
                self._token('True')

            @choice.option
            def _():
                self._token('False')

            choice.expecting('True', 'False')

    @rule()
    def _null_(self):
        self._token('None')

    @rule('EOF')
    def _eof_(self):
        self._token('$')
        self._cut()


def main(filename, **kwargs):
    if not filename or filename == '-':
        import sys

        text = sys.stdin.read()
    else:
        import pathlib

        text = pathlib.Path(filename).read_text()

    parser = TatSuBootstrapParser()
    return parser.parse(text, filename=filename, **kwargs)


if __name__ == '__main__':
    import json
    from tatsu.util import asjson

    ast = generic_main(main, TatSuBootstrapParser, name='TatSuBootstrap')
    data = asjson(ast)
    print(json.dumps(data, indent=2))
