#!/usr/bin/env python3
#
# CAVEAT UTILITOR
#
#  This file was automatically generated by 竜TatSu v5.18.0b1
#
#     https://pypi.python.org/pypi/tatsu/
#
#  Any changes you make to it will be overwritten the next time
#  the file is generated.
#
# ruff: noqa
# ty: ignore
# mypy: ignore-errors
# pyright: ignore
# type: ignore
# noqa
# fmt: off

from __future__ import annotations

from tatsu import decorators as tatsu
from tatsu.contexts import Ctx
from tatsu.parserconfig import ParserConfig
from tatsu.parsing import Parser, generic_main
from tatsu.tokenizing.buffer import Buffer
from tatsu.tokenizing.textlines import TextLinesTokenizer


KEYWORDS: set[str] = set()


class TatSuBootstrapTokenizer(TextLinesTokenizer):
    def __init__(
        self,
        text, /,
        config: ParserConfig | None = None,
        **settings,
    ) -> None:
        config = ParserConfig.new(
            config=config,
            whitespace=r'(?m)\s+',
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=True,
            comments=r'(?ms)[(][*]\s*((?:.|\n)*?)\s*[*][)]|[\/][*]\s*((?:.|\n)*?)\s*[*][\/]',
            eol_comments=r'(?ms)(?:[#]|[\/][\/])(.*?)$',
            keywords=KEYWORDS,
            start='start',
        )
        assert isinstance(config, ParserConfig)
        config = config.override(**settings)

        super().__init__(text, config=config)


class TatSuBootstrapBuffer(Buffer):  # NOTE: backwards compatibility
    def __init__(
        self,
        text, /,
        config: ParserConfig | None = None,
        **settings,
    ) -> None:
        config = ParserConfig.new(
            config=config,
            whitespace=r'(?m)\s+',
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=True,
            comments=r'(?ms)[(][*]\s*((?:.|\n)*?)\s*[*][)]|[\/][*]\s*((?:.|\n)*?)\s*[*][\/]',
            eol_comments=r'(?ms)(?:[#]|[\/][\/])(.*?)$',
            keywords=KEYWORDS,
            start='start',
        )
        assert isinstance(config, ParserConfig)
        config = config.override(**settings)

        super().__init__(text, config=config)


class TatSuBootstrapParser(Parser):
    def __init__(self, /, config: ParserConfig | None = None, **settings):
        config = ParserConfig.new(config, **settings)
        rulessource = TatSuBootstrapRules()
        assert isinstance(config, ParserConfig)
        tokenizercls = config.tokenizercls or TatSuBootstrapTokenizer

        super().__init__(rulessource, config=config, tokenizercls=tokenizercls)


class TatSuBootstrapRules:
    def __init__(self, /, config: ParserConfig | None = None, **settings):
        config = ParserConfig.new(
            config=config,
            whitespace=r'(?m)\s+',
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=True,
            comments=r'(?ms)[(][*]\s*((?:.|\n)*?)\s*[*][)]|[\/][*]\s*((?:.|\n)*?)\s*[*][\/]',
            eol_comments=r'(?ms)(?:[#]|[\/][\/])(.*?)$',
            keywords=KEYWORDS,
            start='start',
        )
        assert isinstance(config, ParserConfig)
        config = config.override(**settings)
        self._config = config

    @property
    def config(self) -> ParserConfig:
        assert isinstance(self._config, ParserConfig)
        return self._config

    @tatsu.rule
    def start(self, ctx: Ctx):
        self.grammar(ctx)

    @tatsu.rule('Grammar')
    def grammar(self, ctx: Ctx):
        ctx.define(['title'], ['directives', 'keywords', 'rules'])
        with ctx.nameset('title'):
            ctx.constant('TATSU')
        with ctx.loopopt() as cl:
            @cl.exp
            def 〇(ctx: Ctx):
                with ctx.choice() as α:
                    @α.option
                    def 〇(ctx: Ctx):
                        with ctx.nameadd('directives'):
                            self.directive(ctx)

                    @α.option
                    def 〇(ctx: Ctx):
                        with ctx.nameadd('keywords'):
                            self.keyword(ctx)

                    α.expecting('<directive>', '<keyword>')
        with ctx.nameadd('rules'):
            self.rule(ctx)
        with ctx.loopopt() as clβ:
            @clβ.exp
            def 〇(ctx: Ctx):
                with ctx.choice() as α:
                    @α.option
                    def 〇(ctx: Ctx):
                        with ctx.nameadd('rules'):
                            self.rule(ctx)

                    @α.option
                    def 〇(ctx: Ctx):
                        with ctx.nameadd('keywords'):
                            self.keyword(ctx)

                    α.expecting('<keyword>', '<rule>')
        ctx.eofcheck()

    @tatsu.rule
    def directive(self, ctx: Ctx):
        ctx.define(['name', 'value'], [])
        ctx.token('@@')
        with ctx.ifnot_():
            ctx.token('keyword')
        ctx.cut()
        with ctx.group():
            with ctx.choice() as α:
                @α.option
                def 〇(ctx: Ctx):
                    ctx.define(['name', 'value'], [])
                    with ctx.nameset('name'):
                        with ctx.group():
                            with ctx.choice() as β:
                                @β.option
                                def 〇(ctx: Ctx):
                                    ctx.token('comments')

                                @β.option
                                def 〇(ctx: Ctx):
                                    ctx.token('eol_comments')

                                β.expecting('comments', 'eol_comments')
                    ctx.cut()
                    ctx.token('::')
                    ctx.cut()
                    with ctx.nameset('value'):
                        self.regex(ctx)

                @α.option
                def 〇(ctx: Ctx):
                    ctx.define(['name', 'value'], [])
                    with ctx.nameset('name'):
                        with ctx.group():
                            ctx.token('whitespace')
                    ctx.cut()
                    ctx.token('::')
                    ctx.cut()
                    with ctx.nameset('value'):
                        with ctx.group():
                            with ctx.choice() as β:
                                @β.option
                                def 〇(ctx: Ctx):
                                    self.regex(ctx)

                                @β.option
                                def 〇(ctx: Ctx):
                                    self.string(ctx)

                                @β.option
                                def 〇(ctx: Ctx):
                                    ctx.token('None')

                                @β.option
                                def 〇(ctx: Ctx):
                                    ctx.token('False')

                                @β.option
                                def 〇(ctx: Ctx):
                                    ctx.constant('None')

                                β.expecting(
                                    '<regex>',
                                    '<string>',
                                    'False',
                                    'None'
                                )

                @α.option
                def 〇(ctx: Ctx):
                    ctx.define(['name', 'value'], [])
                    with ctx.nameset('name'):
                        with ctx.group():
                            with ctx.choice() as β:
                                @β.option
                                def 〇(ctx: Ctx):
                                    ctx.token('nameguard')

                                @β.option
                                def 〇(ctx: Ctx):
                                    ctx.token('ignorecase')

                                @β.option
                                def 〇(ctx: Ctx):
                                    ctx.token('left_recursion')

                                @β.option
                                def 〇(ctx: Ctx):
                                    ctx.token('parseinfo')

                                @β.option
                                def 〇(ctx: Ctx):
                                    ctx.token('memoization')

                                β.expecting(
                                    'ignorecase',
                                    'left_recursion',
                                    'memoization',
                                    'nameguard',
                                    'parseinfo'
                                )
                    ctx.cut()
                    with ctx.group():
                        with ctx.choice() as β:
                            @β.option
                            def 〇(ctx: Ctx):
                                ctx.define(['value'], [])
                                ctx.token('::')
                                ctx.cut()
                                with ctx.nameset('value'):
                                    self.boolean(ctx)

                            @β.option
                            def 〇(ctx: Ctx):
                                with ctx.nameset('value'):
                                    ctx.constant(True)

                            β.expecting('::')

                @α.option
                def 〇(ctx: Ctx):
                    ctx.define(['name', 'value'], [])
                    with ctx.nameset('name'):
                        with ctx.group():
                            ctx.token('grammar')
                    ctx.cut()
                    ctx.token('::')
                    ctx.cut()
                    with ctx.nameset('value'):
                        self.word(ctx)

                @α.option
                def 〇(ctx: Ctx):
                    ctx.define(['name', 'value'], [])
                    with ctx.nameset('name'):
                        with ctx.group():
                            ctx.token('namechars')
                    ctx.cut()
                    ctx.token('::')
                    ctx.cut()
                    with ctx.nameset('value'):
                        self.string(ctx)

                α.expecting(
                    'comments',
                    'eol_comments',
                    'grammar',
                    'ignorecase',
                    'left_recursion',
                    'memoization',
                    'namechars',
                    'nameguard',
                    'parseinfo',
                    'whitespace'
                )
        ctx.cut()

    @tatsu.rule
    def keywords(self, ctx: Ctx):
        with ctx.loopplus() as cl:
            @cl.exp
            def 〇(ctx: Ctx):
                self.keyword(ctx)

    @tatsu.rule
    def keyword(self, ctx: Ctx):
        ctx.token('@@keyword')
        ctx.cut()
        ctx.token('::')
        ctx.cut()
        with ctx.loopopt() as cl:
            @cl.exp
            def 〇(ctx: Ctx):
                with ctx.nameadd('@'):
                    with ctx.group():
                        with ctx.choice() as α:
                            @α.option
                            def 〇(ctx: Ctx):
                                self.word(ctx)

                            @α.option
                            def 〇(ctx: Ctx):
                                self.string(ctx)

                            α.expecting('<string>', '<word>')
                with ctx.ifnot_():
                    with ctx.group():
                        with ctx.choice() as α:
                            @α.option
                            def 〇(ctx: Ctx):
                                ctx.token(':')

                            @α.option
                            def 〇(ctx: Ctx):
                                ctx.token('=')

                            α.expecting(':', '=')

    @tatsu.rule
    def params(self, ctx: Ctx):
        with ctx.nameadd('@'):
            self.first_param(ctx)
        with ctx.loopopt() as cl:
            @cl.exp
            def 〇(ctx: Ctx):
                ctx.token(',')
                with ctx.nameadd('@'):
                    self.literal(ctx)
                with ctx.ifnot_():
                    ctx.token('=')
                ctx.cut()

    @tatsu.rule
    def first_param(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                self.path(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.literal(ctx)

            α.expecting(
                '(?!\\d)\\w+(?:::(?!\\d)\\w+)+',
                '<boolean>',
                '<float>',
                '<hex>',
                '<int>',
                '<literal>',
                '<null>',
                '<path>',
                '<raw_string>',
                '<string>',
                '<word>'
            )

    @tatsu.rule
    def kwparams(self, ctx: Ctx):
        with ctx.gatherplus() as g:
            @g.sep
            def 〇(ctx: Ctx):
                ctx.token(',')

            @g.exp
            def 〇(ctx: Ctx):
                self.pair(ctx)

    @tatsu.rule
    def the_params_at_last(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                with ctx.nameset('kwparams'):
                    self.kwparams(ctx)

            @α.option
            def 〇(ctx: Ctx):
                ctx.define(['kwparams', 'params'], [])
                with ctx.nameset('params'):
                    self.params(ctx)
                ctx.token(',')
                ctx.cut()
                with ctx.nameset('kwparams'):
                    self.kwparams(ctx)

            @α.option
            def 〇(ctx: Ctx):
                with ctx.nameset('params'):
                    self.params(ctx)

            α.expecting('<kwparams>', '<params>')

    @tatsu.rule
    def paramdef(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                ctx.define(['kwparams', 'params'], [])
                ctx.token('[')
                ctx.cut()
                with ctx.choice() as β:
                    @β.option
                    def 〇(ctx: Ctx):
                        with ctx.nameset('kwparams'):
                            self.kwparams(ctx)

                    @β.option
                    def 〇(ctx: Ctx):
                        ctx.define(['kwparams', 'params'], [])
                        with ctx.nameset('params'):
                            self.params(ctx)
                        ctx.token(',')
                        ctx.cut()
                        with ctx.nameset('kwparams'):
                            self.kwparams(ctx)

                    @β.option
                    def 〇(ctx: Ctx):
                        with ctx.nameset('params'):
                            self.params(ctx)

                    β.expecting('<kwparams>', '<params>')
                ctx.token(']')

            @α.option
            def 〇(ctx: Ctx):
                ctx.define(['kwparams', 'params'], [])
                ctx.token('(')
                ctx.cut()
                with ctx.choice() as β:
                    @β.option
                    def 〇(ctx: Ctx):
                        with ctx.nameset('kwparams'):
                            self.kwparams(ctx)

                    @β.option
                    def 〇(ctx: Ctx):
                        ctx.define(['kwparams', 'params'], [])
                        with ctx.nameset('params'):
                            self.params(ctx)
                        ctx.token(',')
                        ctx.cut()
                        with ctx.nameset('kwparams'):
                            self.kwparams(ctx)

                    @β.option
                    def 〇(ctx: Ctx):
                        with ctx.nameset('params'):
                            self.params(ctx)

                    β.expecting('<kwparams>', '<params>')
                ctx.token(')')

            @α.option
            def 〇(ctx: Ctx):
                ctx.define(['params'], [])
                ctx.token('::')
                ctx.cut()
                with ctx.nameset('params'):
                    self.params(ctx)

            α.expecting('(', '::', '[')

    @tatsu.rule('Rule')
    def rule(self, ctx: Ctx):
        ctx.define(['base', 'decorators', 'exp', 'kwparams', 'name', 'params'], [])
        with ctx.nameset('decorators'):
            with ctx.loopopt() as cl:
                @cl.exp
                def 〇(ctx: Ctx):
                    self.decorator(ctx)
        with ctx.nameset('name'):
            self.name(ctx)
        ctx.cut()
        with ctx.optional():
            with ctx.choice() as α:
                @α.option
                def 〇(ctx: Ctx):
                    ctx.define(['kwparams', 'params'], [])
                    ctx.token('[')
                    ctx.cut()
                    with ctx.choice() as β:
                        @β.option
                        def 〇(ctx: Ctx):
                            with ctx.nameset('kwparams'):
                                self.kwparams(ctx)

                        @β.option
                        def 〇(ctx: Ctx):
                            ctx.define(['kwparams', 'params'], [])
                            with ctx.nameset('params'):
                                self.params(ctx)
                            ctx.token(',')
                            ctx.cut()
                            with ctx.nameset('kwparams'):
                                self.kwparams(ctx)

                        @β.option
                        def 〇(ctx: Ctx):
                            with ctx.nameset('params'):
                                self.params(ctx)

                        β.expecting('<kwparams>', '<params>')
                    ctx.token(']')

                @α.option
                def 〇(ctx: Ctx):
                    ctx.define(['kwparams', 'params'], [])
                    ctx.token('(')
                    ctx.cut()
                    with ctx.choice() as β:
                        @β.option
                        def 〇(ctx: Ctx):
                            with ctx.nameset('kwparams'):
                                self.kwparams(ctx)

                        @β.option
                        def 〇(ctx: Ctx):
                            ctx.define(['kwparams', 'params'], [])
                            with ctx.nameset('params'):
                                self.params(ctx)
                            ctx.token(',')
                            ctx.cut()
                            with ctx.nameset('kwparams'):
                                self.kwparams(ctx)

                        @β.option
                        def 〇(ctx: Ctx):
                            with ctx.nameset('params'):
                                self.params(ctx)

                        β.expecting('<kwparams>', '<params>')
                    ctx.token(')')

                @α.option
                def 〇(ctx: Ctx):
                    ctx.define(['params'], [])
                    ctx.token('::')
                    ctx.cut()
                    with ctx.nameset('params'):
                        self.params(ctx)

                α.expecting('(', '::', '[')
        with ctx.optional():
            ctx.define(['base'], [])
            ctx.token('<')
            ctx.cut()
            with ctx.nameset('base'):
                self.known_name(ctx)
        ctx.void()
        ctx.pattern(r'=|:=?')
        ctx.cut()
        with ctx.nameset('exp'):
            self.expre(ctx)
        self.ENDRULE(ctx)
        ctx.cut()

    @tatsu.rule
    def ENDRULE(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                with ctx.if_():
                    self.UNINDENTED(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.EMPTYLINE(ctx)
                with ctx.optional():
                    ctx.token(';')

            @α.option
            def 〇(ctx: Ctx):
                ctx.eofcheck()

            @α.option
            def 〇(ctx: Ctx):
                ctx.token(';')

            α.expecting(
                '(?:\\s*(?:\\r?\\n|\\r)){2,}',
                '(?=\\s*(?:\\r?\\n|\\r)[^\\s])',
                ';',
                '<EMPTYLINE>',
                '<UNINDENTED>'
            )

    @tatsu.rule
    def UNINDENTED(self, ctx: Ctx):
        ctx.pattern(r'(?=\s*(?:\r?\n|\r)[^\s])')

    @tatsu.rule
    def EMPTYLINE(self, ctx: Ctx):
        ctx.pattern(r'(?:\s*(?:\r?\n|\r)){2,}')

    @tatsu.rule
    def decorator(self, ctx: Ctx):
        ctx.token('@')
        with ctx.ifnot_():
            ctx.token('@')
        ctx.cut()
        with ctx.nameset('@'):
            with ctx.group():
                with ctx.choice() as α:
                    @α.option
                    def 〇(ctx: Ctx):
                        ctx.token('override')

                    @α.option
                    def 〇(ctx: Ctx):
                        ctx.token('name')

                    @α.option
                    def 〇(ctx: Ctx):
                        ctx.token('isname')

                    @α.option
                    def 〇(ctx: Ctx):
                        ctx.token('nomemo')

                    α.expecting('isname', 'name', 'nomemo', 'override')

    @tatsu.rule
    def pair(self, ctx: Ctx):
        with ctx.nameadd('@'):
            self.word(ctx)
        ctx.token('=')
        ctx.cut()
        with ctx.nameadd('@'):
            self.literal(ctx)

    @tatsu.rule
    def expre(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                self.choice(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.sequence(ctx)

            α.expecting(
                ';',
                '<EMPTYLINE>',
                '<ENDRULE>',
                '<UNINDENTED>',
                '<choice>',
                '<element>',
                '<option>',
                '<sequence>',
                '|'
            )

    @tatsu.rule('Choice')
    def choice(self, ctx: Ctx):
        with ctx.optional():
            ctx.token('|')
            ctx.cut()
        with ctx.nameadd('@'):
            self.option(ctx)
        with ctx.loopplus() as cl:
            @cl.exp
            def 〇(ctx: Ctx):
                ctx.token('|')
                ctx.cut()
                with ctx.nameadd('@'):
                    self.option(ctx)

    @tatsu.rule('Option')
    def option(self, ctx: Ctx):
        with ctx.nameset('@'):
            self.sequence(ctx)

    @tatsu.rule('Sequence')
    def sequence(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                with ctx.if_():
                    with ctx.group():
                        self.element(ctx)
                        ctx.token(',')
                with ctx.gatherplus() as g:
                    @g.sep
                    def 〇(ctx: Ctx):
                        ctx.token(',')

                    @g.exp
                    def 〇(ctx: Ctx):
                        self.element(ctx)

            @α.option
            def 〇(ctx: Ctx):
                with ctx.loopplus() as cl:
                    @cl.exp
                    def 〇(ctx: Ctx):
                        with ctx.ifnot_():
                            self.ENDRULE(ctx)
                        self.element(ctx)

            α.expecting(
                '(?:\\s*(?:\\r?\\n|\\r)){2,}',
                '(?=\\s*(?:\\r?\\n|\\r)[^\\s])',
                ';',
                '<EMPTYLINE>',
                '<ENDRULE>',
                '<UNINDENTED>',
                '<element>',
                '<named>',
                '<override>',
                '<rule_include>',
                '<term>'
            )

    @tatsu.rule
    def element(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                self.rule_include(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.named(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.override(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.term(ctx)

            α.expecting(
                '<atom>',
                '<closure>',
                '<cut>',
                '<cut_deprecated>',
                '<empty_closure>',
                '<gather>',
                '<join>',
                '<left_join>',
                '<lookahead>',
                '<named>',
                '<named_list>',
                '<named_single>',
                '<negative_lookahead>',
                '<optional>',
                '<override>',
                '<override_list>',
                '<override_single>',
                '<override_single_deprecated>',
                '<positive_closure>',
                '<right_join>',
                '<rule_include>',
                '<skip_to>',
                '<term>',
                '<void>',
                '>'
            )

    @tatsu.rule('RuleInclude')
    def rule_include(self, ctx: Ctx):
        ctx.token('>')
        ctx.cut()
        with ctx.nameset('@'):
            self.known_name(ctx)

    @tatsu.rule
    def named(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                self.named_list(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.named_single(ctx)

            α.expecting('<name>', '<named_list>', '<named_single>')

    @tatsu.rule('NamedList')
    def named_list(self, ctx: Ctx):
        ctx.define(['exp', 'name'], [])
        with ctx.nameset('name'):
            self.name(ctx)
        ctx.token('+:')
        ctx.cut()
        with ctx.nameset('exp'):
            self.term(ctx)

    @tatsu.rule('Named')
    def named_single(self, ctx: Ctx):
        ctx.define(['exp', 'name'], [])
        with ctx.nameset('name'):
            self.name(ctx)
        ctx.token(':')
        ctx.cut()
        with ctx.nameset('exp'):
            self.term(ctx)

    @tatsu.rule
    def override(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                self.override_list(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.override_single(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.override_single_deprecated(ctx)

            α.expecting(
                '<override_list>',
                '<override_single>',
                '<override_single_deprecated>',
                '@',
                '@+:',
                '@:'
            )

    @tatsu.rule('OverrideList')
    def override_list(self, ctx: Ctx):
        ctx.token('@+:')
        ctx.cut()
        with ctx.nameset('@'):
            self.term(ctx)

    @tatsu.rule('Override')
    def override_single(self, ctx: Ctx):
        ctx.token('@:')
        ctx.cut()
        with ctx.nameset('@'):
            self.term(ctx)

    @tatsu.rule('Override')
    def override_single_deprecated(self, ctx: Ctx):
        ctx.token('@')
        ctx.cut()
        with ctx.nameset('@'):
            self.term(ctx)

    @tatsu.rule
    def term(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                self.void(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.gather(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.join(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.left_join(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.right_join(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.empty_closure(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.positive_closure(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.closure(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.optional(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.skip_to(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.lookahead(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.negative_lookahead(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.cut(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.cut_deprecated(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.atom(ctx)

            α.expecting(
                '!',
                '&',
                '(',
                '()',
                '->',
                '<alert>',
                '<atom>',
                '<call>',
                '<closure>',
                '<constant>',
                '<cut>',
                '<cut_deprecated>',
                '<dot>',
                '<empty_closure>',
                '<eof>',
                '<gather>',
                '<group>',
                '<join>',
                '<left_join>',
                '<lookahead>',
                '<negative_lookahead>',
                '<optional>',
                '<pattern>',
                '<positive_closure>',
                '<right_join>',
                '<skip_to>',
                '<token>',
                '<void>',
                '>>',
                '[',
                '{',
                '{}',
                '~'
            )

    @tatsu.rule('Group')
    def group(self, ctx: Ctx):
        ctx.token('(')
        ctx.cut()
        with ctx.nameset('@'):
            self.expre(ctx)
        ctx.token(')')
        ctx.cut()

    @tatsu.rule
    def gather(self, ctx: Ctx):
        with ctx.if_():
            with ctx.group():
                self.atom(ctx)
                ctx.token('.{')
        ctx.cut()
        with ctx.group():
            with ctx.choice() as α:
                @α.option
                def 〇(ctx: Ctx):
                    self.positive_gather(ctx)

                @α.option
                def 〇(ctx: Ctx):
                    self.normal_gather(ctx)

                α.expecting('<normal_gather>', '<positive_gather>')

    @tatsu.rule('PositiveGather')
    def positive_gather(self, ctx: Ctx):
        ctx.define(['exp', 'sep'], [])
        with ctx.nameset('sep'):
            self.atom(ctx)
        ctx.token('.{')
        with ctx.nameset('exp'):
            self.expre(ctx)
        ctx.token('}')
        with ctx.group():
            with ctx.choice() as α:
                @α.option
                def 〇(ctx: Ctx):
                    ctx.token('+')

                @α.option
                def 〇(ctx: Ctx):
                    ctx.token('-')

                α.expecting('+', '-')
        ctx.cut()

    @tatsu.rule('Gather')
    def normal_gather(self, ctx: Ctx):
        ctx.define(['exp', 'sep'], [])
        with ctx.nameset('sep'):
            self.atom(ctx)
        ctx.token('.{')
        ctx.cut()
        with ctx.nameset('exp'):
            self.expre(ctx)
        ctx.token('}')
        with ctx.optional():
            ctx.token('*')
            ctx.cut()
        ctx.cut()

    @tatsu.rule
    def join(self, ctx: Ctx):
        with ctx.if_():
            with ctx.group():
                self.atom(ctx)
                ctx.token('%{')
        ctx.cut()
        with ctx.group():
            with ctx.choice() as α:
                @α.option
                def 〇(ctx: Ctx):
                    self.positive_join(ctx)

                @α.option
                def 〇(ctx: Ctx):
                    self.normal_join(ctx)

                α.expecting('<normal_join>', '<positive_join>')

    @tatsu.rule('PositiveJoin')
    def positive_join(self, ctx: Ctx):
        ctx.define(['exp', 'sep'], [])
        with ctx.nameset('sep'):
            self.atom(ctx)
        ctx.token('%{')
        with ctx.nameset('exp'):
            self.expre(ctx)
        ctx.token('}')
        with ctx.group():
            with ctx.choice() as α:
                @α.option
                def 〇(ctx: Ctx):
                    ctx.token('+')

                @α.option
                def 〇(ctx: Ctx):
                    ctx.token('-')

                α.expecting('+', '-')
        ctx.cut()

    @tatsu.rule('Join')
    def normal_join(self, ctx: Ctx):
        ctx.define(['exp', 'sep'], [])
        with ctx.nameset('sep'):
            self.atom(ctx)
        ctx.token('%{')
        ctx.cut()
        with ctx.nameset('exp'):
            self.expre(ctx)
        ctx.token('}')
        with ctx.optional():
            ctx.token('*')
            ctx.cut()
        ctx.cut()

    @tatsu.rule('LeftJoin')
    def left_join(self, ctx: Ctx):
        ctx.define(['exp', 'sep'], [])
        with ctx.nameset('sep'):
            self.atom(ctx)
        ctx.token('<{')
        ctx.cut()
        with ctx.nameset('exp'):
            self.expre(ctx)
        ctx.token('}')
        with ctx.group():
            with ctx.choice() as α:
                @α.option
                def 〇(ctx: Ctx):
                    ctx.token('+')

                @α.option
                def 〇(ctx: Ctx):
                    ctx.token('-')

                α.expecting('+', '-')
        ctx.cut()

    @tatsu.rule('RightJoin')
    def right_join(self, ctx: Ctx):
        ctx.define(['exp', 'sep'], [])
        with ctx.nameset('sep'):
            self.atom(ctx)
        ctx.token('>{')
        ctx.cut()
        with ctx.nameset('exp'):
            self.expre(ctx)
        ctx.token('}')
        with ctx.group():
            with ctx.choice() as α:
                @α.option
                def 〇(ctx: Ctx):
                    ctx.token('+')

                @α.option
                def 〇(ctx: Ctx):
                    ctx.token('-')

                α.expecting('+', '-')
        ctx.cut()

    @tatsu.rule('PositiveClosure')
    def positive_closure(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                ctx.token('{')
                with ctx.nameset('@'):
                    self.expre(ctx)
                ctx.token('}')
                with ctx.group():
                    with ctx.choice() as β:
                        @β.option
                        def 〇(ctx: Ctx):
                            ctx.token('-')

                        @β.option
                        def 〇(ctx: Ctx):
                            ctx.token('+')

                        β.expecting('+', '-')
                ctx.cut()

            @α.option
            def 〇(ctx: Ctx):
                with ctx.nameset('@'):
                    self.atom(ctx)
                ctx.token('+')
                ctx.cut()

            α.expecting(
                '(',
                '<alert>',
                '<atom>',
                '<call>',
                '<constant>',
                '<dot>',
                '<eof>',
                '<group>',
                '<pattern>',
                '<token>',
                '{'
            )

    @tatsu.rule('Closure')
    def closure(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                ctx.token('{')
                with ctx.nameset('@'):
                    self.expre(ctx)
                ctx.token('}')
                with ctx.optional():
                    ctx.token('*')
                ctx.cut()

            @α.option
            def 〇(ctx: Ctx):
                with ctx.nameset('@'):
                    self.atom(ctx)
                ctx.token('*')
                ctx.cut()

            α.expecting(
                '(',
                '<alert>',
                '<atom>',
                '<call>',
                '<constant>',
                '<dot>',
                '<eof>',
                '<group>',
                '<pattern>',
                '<token>',
                '{'
            )

    @tatsu.rule('EmptyClosure')
    def empty_closure(self, ctx: Ctx):
        ctx.token('{}')
        ctx.cut()
        with ctx.nameset('@'):
            ctx.void()

    @tatsu.rule('Optional')
    def optional(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                ctx.token('[')
                ctx.cut()
                with ctx.nameset('@'):
                    self.expre(ctx)
                ctx.token(']')
                ctx.cut()

            @α.option
            def 〇(ctx: Ctx):
                with ctx.nameset('@'):
                    self.atom(ctx)
                with ctx.ifnot_():
                    with ctx.group():
                        with ctx.choice() as β:
                            @β.option
                            def 〇(ctx: Ctx):
                                ctx.token('?"')

                            @β.option
                            def 〇(ctx: Ctx):
                                ctx.token("?'")

                            @β.option
                            def 〇(ctx: Ctx):
                                ctx.token('?/')

                            β.expecting("?'", '?"', '?/')
                ctx.token('?')
                ctx.cut()

            α.expecting(
                '(',
                '<alert>',
                '<atom>',
                '<call>',
                '<constant>',
                '<dot>',
                '<eof>',
                '<group>',
                '<pattern>',
                '<token>',
                '['
            )

    @tatsu.rule('Lookahead')
    def lookahead(self, ctx: Ctx):
        ctx.token('&')
        ctx.cut()
        with ctx.nameset('@'):
            self.term(ctx)

    @tatsu.rule('NegativeLookahead')
    def negative_lookahead(self, ctx: Ctx):
        ctx.token('!')
        ctx.cut()
        with ctx.nameset('@'):
            self.term(ctx)

    @tatsu.rule('SkipTo')
    def skip_to(self, ctx: Ctx):
        ctx.token('->')
        ctx.cut()
        with ctx.nameset('@'):
            self.term(ctx)

    @tatsu.rule
    def atom(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                self.group(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.token(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.alert(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.constant(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.call(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.pattern(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.dot(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.eof(ctx)

            α.expecting(
                '$',
                '(',
                '/./',
                '<alert>',
                '<call>',
                '<constant>',
                '<dot>',
                '<eof>',
                '<group>',
                '<pattern>',
                '<raw_string>',
                '<regex>',
                '<string>',
                '<token>',
                '<word>',
                '\\^+',
                '`'
            )

    @tatsu.rule('Call')
    def call(self, ctx: Ctx):
        self.word(ctx)

    @tatsu.rule('Void')
    def void(self, ctx: Ctx):
        ctx.token('()')
        ctx.cut()

    @tatsu.rule('Fail')
    def fail(self, ctx: Ctx):
        ctx.token('!()')
        ctx.cut()

    @tatsu.rule('Cut')
    def cut(self, ctx: Ctx):
        ctx.token('~')
        ctx.cut()

    @tatsu.rule('Cut')
    def cut_deprecated(self, ctx: Ctx):
        ctx.token('>>')
        ctx.cut()

    @tatsu.rule
    def known_name(self, ctx: Ctx):
        self.name(ctx)
        ctx.cut()

    @tatsu.rule
    def name(self, ctx: Ctx):
        self.word(ctx)

    @tatsu.rule('Constant')
    def constant(self, ctx: Ctx):
        with ctx.if_():
            ctx.token('`')
        with ctx.group():
            with ctx.choice() as α:
                @α.option
                def 〇(ctx: Ctx):
                    ctx.pattern(r'(?ms)```((?:.|\n)*?)```')

                @α.option
                def 〇(ctx: Ctx):
                    ctx.token('`')
                    with ctx.nameset('@'):
                        self.literal(ctx)
                    ctx.token('`')

                @α.option
                def 〇(ctx: Ctx):
                    ctx.pattern(r'`(.*?)`')

                α.expecting('(?ms)```((?:.|\\n)*?)```', '`', '`(.*?)`')

    @tatsu.rule('Alert')
    def alert(self, ctx: Ctx):
        ctx.define(['level', 'message'], [])
        with ctx.nameset('level'):
            ctx.pattern(r'\^+')
        with ctx.nameset('message'):
            self.constant(ctx)

    @tatsu.rule('Token')
    def token(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                self.string(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.raw_string(ctx)

            α.expecting(
                '<doublequoted>',
                '<multiline_string>',
                '<raw_string>',
                '<singlequoted>',
                '<string>',
                'r'
            )

    @tatsu.rule
    def literal(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                self.string(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.raw_string(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.boolean(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.word(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.hex(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.float(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.int(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.null(ctx)

            α.expecting(
                '(?!\\d)\\w+',
                '0[xX](?:\\d|[a-fA-F])+',
                '<boolean>',
                '<doublequoted>',
                '<float>',
                '<hex>',
                '<int>',
                '<multiline_string>',
                '<null>',
                '<raw_string>',
                '<singlequoted>',
                '<string>',
                '<word>',
                'False',
                'None',
                'True',
                '[-+]?(?:\\d+\\.\\d*|\\d*\\.\\d+)(?:[Ee][-+]?\\d+)?',
                '[-+]?\\d+',
                'r'
            )

    @tatsu.rule
    def string(self, ctx: Ctx):
        with ctx.group():
            with ctx.choice() as α:
                @α.option
                def 〇(ctx: Ctx):
                    self.multiline_string(ctx)

                @α.option
                def 〇(ctx: Ctx):
                    self.singlequoted(ctx)

                @α.option
                def 〇(ctx: Ctx):
                    self.doublequoted(ctx)

                α.expecting(
                    "(?ms)'''((?:\\\\\\\\|\\\\.|(?!''').)*?)'''",
                    '(?ms)"""((?:\\\\\\\\|\\\\.|(?!""").)*?)"""',
                    '<DOUBLEQUOTED>',
                    '<SINGLEQUOTED>',
                    '<doublequoted>',
                    '<multiline_string>',
                    '<singlequoted>'
                )

    @tatsu.rule
    def singlequoted(self, ctx: Ctx):
        self.SINGLEQUOTED(ctx)

    @tatsu.rule
    def doublequoted(self, ctx: Ctx):
        self.DOUBLEQUOTED(ctx)

    @tatsu.rule
    def raw_string(self, ctx: Ctx):
        ctx.pattern(r'r')
        with ctx.nameset('@'):
            self.STRING(ctx)

    @tatsu.rule
    def STRING(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                self.SINGLEQUOTED(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.DOUBLEQUOTED(ctx)

            α.expecting(
                "'((?:[^'\\n]|\\\\'|\\\\\\\\)*?)'",
                '"((?:[^"\\n]|\\\\"|\\\\\\\\)*?)"',
                '<DOUBLEQUOTED>',
                '<SINGLEQUOTED>'
            )

    @tatsu.rule
    def SINGLEQUOTED(self, ctx: Ctx):
        ctx.pattern(r"'((?:[^'\n]|\\'|\\\\)*?)'")
        ctx.cut()

    @tatsu.rule
    def DOUBLEQUOTED(self, ctx: Ctx):
        ctx.pattern(r'"((?:[^"\n]|\\"|\\\\)*?)"')
        ctx.cut()

    @tatsu.rule
    def multiline_string(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                ctx.pattern(r"(?ms)'''((?:\\\\|\\.|(?!''').)*?)'''")
                ctx.cut()

            @α.option
            def 〇(ctx: Ctx):
                ctx.pattern(r'(?ms)"""((?:\\\\|\\.|(?!""").)*?)"""')
                ctx.cut()

            α.expecting(
                "(?ms)'''((?:\\\\\\\\|\\\\.|(?!''').)*?)'''",
                '(?ms)"""((?:\\\\\\\\|\\\\.|(?!""").)*?)"""'
            )

    @tatsu.rule
    def hex(self, ctx: Ctx):
        ctx.pattern(r'0[xX](?:\d|[a-fA-F])+')

    @tatsu.rule
    def float(self, ctx: Ctx):
        ctx.pattern(r'[-+]?(?:\d+\.\d*|\d*\.\d+)(?:[Ee][-+]?\d+)?')

    @tatsu.rule
    def int(self, ctx: Ctx):
        ctx.pattern(r'[-+]?\d+')

    @tatsu.rule
    def path(self, ctx: Ctx):
        ctx.pattern(r'(?!\d)\w+(?:::(?!\d)\w+)+')

    @tatsu.rule
    def word(self, ctx: Ctx):
        ctx.pattern(r'(?!\d)\w+')

    @tatsu.rule('Dot')
    def dot(self, ctx: Ctx):
        ctx.token('/./')

    @tatsu.rule('Pattern')
    def pattern(self, ctx: Ctx):
        self.regex(ctx)

    @tatsu.rule
    def regex(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                self.REGEX(ctx)

            @α.option
            def 〇(ctx: Ctx):
                ctx.token('?')
                with ctx.nameset('@'):
                    self.STRING(ctx)

            @α.option
            def 〇(ctx: Ctx):
                self.deprecated_regex(ctx)

            α.expecting(
                '(?ms)/((?:[^/\\\\]|\\\\/|\\\\.)*)/',
                '(?ms)\\?/((?:[^/\\\\]|\\\\/|\\\\.)*)/\\?',
                '<REGEX>',
                '<deprecated_regex>',
                '?'
            )

    @tatsu.rule
    def REGEX(self, ctx: Ctx):
        ctx.pattern(r'(?ms)/((?:[^/\\]|\\/|\\.)*)/')
        ctx.cut()

    @tatsu.rule
    def deprecated_regex(self, ctx: Ctx):
        ctx.pattern(r'(?ms)\?/((?:[^/\\]|\\/|\\.)*)/\?')
        ctx.cut()
        ctx.alert('deprecated regex syntax', 2)

    @tatsu.rule
    def boolean(self, ctx: Ctx):
        with ctx.choice() as α:
            @α.option
            def 〇(ctx: Ctx):
                ctx.token('True')

            @α.option
            def 〇(ctx: Ctx):
                ctx.token('False')

            α.expecting('False', 'True')

    @tatsu.rule
    def null(self, ctx: Ctx):
        ctx.token('None')

    @tatsu.rule('EOF')
    def eof(self, ctx: Ctx):
        ctx.token('$')
        ctx.cut()


def main(filename, **kwargs):
    if not filename or filename == '-':
        import sys

        text = sys.stdin.read()
    else:
        import pathlib

        text = pathlib.Path(filename).read_text()

    parser = TatSuBootstrapParser()
    return parser.parse(text, filename=filename, **kwargs)


if __name__ == '__main__':
    import json
    from tatsu.util import asjson

    ast = generic_main(main, TatSuBootstrapParser, name='TatSuBootstrap')
    data = asjson(ast)
    print(json.dumps(data, indent=2))
