#!/usr/bin/env python3

# CAVEAT UTILITOR
#
#  This file was automatically generated by 竜TatSu.
#
#     https://pypi.python.org/pypi/tatsu/
#
#  Any changes you make to it will be overwritten the next time
#  the file is generated.

# ruff: noqa: RUF100, C405, COM812, I001, F401, PLR1702, PLC2801, SIM117
# ruff: noqa: PL2401, PLC2402, PLC2403
# E303
# fmt: off

from __future__ import annotations

from typing import Any

from tatsu.buffering import Buffer
from tatsu.infos import ParserConfig
from tatsu.parsing import Parser, leftrec, nomemo, isname, generic_main, rule
from tatsu.tokenizing.textlines import TextLinesTokenizer

__all__ = ['TatSuBootstrapTokenizer', 'TatSuBootstrapParser', 'main']


KEYWORDS: set[str] = set()


class TatSuBootstrapTokenizer(TextLinesTokenizer):
    def __init__(self, text, /, config: ParserConfig | None = None, **settings):
        config = ParserConfig.new(
            config,
            whitespace=r'(?m)\s+',
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=True,
            comments=r'(?ms)[(][*]\s*((?:.|\n)*?)\s*[*][)]|[\/][*]\s*((?:.|\n)*?)\s*[*][\/]',
            eol_comments=r'(?ms)(?:[#]|[\/][\/])(.*?)$',
            keywords=KEYWORDS,
            start='start',
        )
        config = config.override(**settings)

        super().__init__(text, config=config)


class TatSuBootstrapBuffer(Buffer):  # NOTE: backwards compatibility
    def __init__(self, text, /, config: ParserConfig | None = None, **settings):
        config = ParserConfig.new(
            config,
            whitespace=r'(?m)\s+',
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=True,
            comments=r'(?ms)[(][*]\s*((?:.|\n)*?)\s*[*][)]|[\/][*]\s*((?:.|\n)*?)\s*[*][\/]',
            eol_comments=r'(?ms)(?:[#]|[\/][\/])(.*?)$',
            keywords=KEYWORDS,
            start='start',
        )
        config = config.override(**settings)

        super().__init__(text, config=config)


class TatSuBootstrapParser(Parser):
    def __init__(self, /, config: ParserConfig | None = None, **settings):
        config = ParserConfig.new(
            config,
            whitespace=r'(?m)\s+',
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=True,
            comments=r'(?ms)[(][*]\s*((?:.|\n)*?)\s*[*][)]|[\/][*]\s*((?:.|\n)*?)\s*[*][\/]',
            eol_comments=r'(?ms)(?:[#]|[\/][\/])(.*?)$',
            keywords=KEYWORDS,
            start='start',
        )
        config = config.override(**settings)

        super().__init__(
            config=config,
            tokenizercls=config.tokenizercls or TatSuBootstrapTokenizer,
        )

    @rule()
    def _start_(self, ss: Any = None):
        self._grammar_(ss)

    @rule('Grammar')
    def _grammar_(self, _ss: Any = None):
        with self._setname('title'):
            self._constant('TATSU')

        def block0():
            with self._choice() as choice:
                @choice.option
                def _():
                    with self._addname('directives'):
                        self._directive_(_ss)

                @choice.option
                def _():
                    with self._addname('keywords'):
                        self._keyword_(_ss)

                choice.expecting('<directive>', '<keyword>')

        self._closure(block0)
        with self._addname('rules'):
            self._rule_(_ss)

        def block1():
            with self._choice() as choice:
                @choice.option
                def _():
                    with self._addname('rules'):
                        self._rule_(_ss)

                @choice.option
                def _():
                    with self._addname('keywords'):
                        self._keyword_(_ss)

                choice.expecting('<keyword>', '<rule>')

        self._closure(block1)
        self._check_eof()
        self._define(['title'], ['directives', 'keywords', 'rules'])

    @rule()
    def _directive_(self, _ss: Any = None):
        self._token('@@')
        with self._ifnot():
            self._token('keyword')
        self._cut()
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    with self._setname('name'):
                        with self._group():
                            with self._choice() as choice:
                                @choice.option
                                def _():
                                    self._token('comments')

                                @choice.option
                                def _():
                                    self._token('eol_comments')

                                choice.expecting('comments', 'eol_comments')
                    self._cut()
                    self._token('::')
                    self._cut()
                    with self._setname('value'):
                        self._regex_(_ss)
                    self._define(['name', 'value'], [])

                @choice.option
                def _():
                    with self._setname('name'):
                        with self._group():
                            self._token('whitespace')
                    self._cut()
                    self._token('::')
                    self._cut()
                    with self._setname('value'):
                        with self._group():
                            with self._choice() as choice:
                                @choice.option
                                def _():
                                    self._regex_(_ss)

                                @choice.option
                                def _():
                                    self._string_(_ss)

                                @choice.option
                                def _():
                                    self._token('None')

                                @choice.option
                                def _():
                                    self._token('False')

                                @choice.option
                                def _():
                                    self._constant('None')

                                choice.expecting(
                                    '<regex>',
                                    '<string>',
                                    'False',
                                    'None'
                                )
                    self._define(['name', 'value'], [])

                @choice.option
                def _():
                    with self._setname('name'):
                        with self._group():
                            with self._choice() as choice:
                                @choice.option
                                def _():
                                    self._token('nameguard')

                                @choice.option
                                def _():
                                    self._token('ignorecase')

                                @choice.option
                                def _():
                                    self._token('left_recursion')

                                @choice.option
                                def _():
                                    self._token('parseinfo')

                                @choice.option
                                def _():
                                    self._token('memoization')

                                choice.expecting(
                                    'ignorecase',
                                    'left_recursion',
                                    'memoization',
                                    'nameguard',
                                    'parseinfo'
                                )
                    self._cut()
                    with self._group():
                        with self._choice() as choice:
                            @choice.option
                            def _():
                                self._token('::')
                                self._cut()
                                with self._setname('value'):
                                    self._boolean_(_ss)
                                self._define(['value'], [])

                            @choice.option
                            def _():
                                with self._setname('value'):
                                    self._constant(True)

                            choice.expecting('::')
                    self._define(['name', 'value'], [])

                @choice.option
                def _():
                    with self._setname('name'):
                        with self._group():
                            self._token('grammar')
                    self._cut()
                    self._token('::')
                    self._cut()
                    with self._setname('value'):
                        self._word_(_ss)
                    self._define(['name', 'value'], [])

                @choice.option
                def _():
                    with self._setname('name'):
                        with self._group():
                            self._token('namechars')
                    self._cut()
                    self._token('::')
                    self._cut()
                    with self._setname('value'):
                        self._string_(_ss)
                    self._define(['name', 'value'], [])

                choice.expecting(
                    'comments',
                    'eol_comments',
                    'grammar',
                    'ignorecase',
                    'left_recursion',
                    'memoization',
                    'namechars',
                    'nameguard',
                    'parseinfo',
                    'whitespace'
                )
        self._cut()
        self._define(['name', 'value'], [])

    @rule()
    def _keywords_(self, _ss: Any = None):

        def block0():
            self._keywords_(_ss)

        self._positive_closure(block0)

    @rule()
    def _keyword_(self, _ss: Any = None):
        self._token('@@keyword')
        self._cut()
        self._token('::')
        self._cut()

        def block0():
            with self._addname('@'):
                with self._group():
                    with self._choice() as choice:
                        @choice.option
                        def _():
                            self._word_(_ss)

                        @choice.option
                        def _():
                            self._string_(_ss)

                        choice.expecting('<string>', '<word>')
            with self._ifnot():
                with self._group():
                    with self._choice() as choice:
                        @choice.option
                        def _():
                            self._token(':')

                        @choice.option
                        def _():
                            self._token('=')

                        choice.expecting(':', '=')

        self._closure(block0)

    @rule()
    def _the_params_at_last_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                with self._setname('kwparams'):
                    self._kwparams_(_ss)

            @choice.option
            def _():
                with self._setname('params'):
                    self._params_(_ss)
                self._token(',')
                self._cut()
                with self._setname('kwparams'):
                    self._kwparams_(_ss)
                self._define(['kwparams', 'params'], [])

            @choice.option
            def _():
                with self._setname('params'):
                    self._params_(_ss)

            choice.expecting('<kwparams>', '<params>')

    @rule()
    def _paramdef_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                self._token('[')
                self._cut()
                with self._choice() as choice:
                    @choice.option
                    def _():
                        with self._setname('kwparams'):
                            self._kwparams_(_ss)

                    @choice.option
                    def _():
                        with self._setname('params'):
                            self._params_(_ss)
                        self._token(',')
                        self._cut()
                        with self._setname('kwparams'):
                            self._kwparams_(_ss)
                        self._define(['kwparams', 'params'], [])

                    @choice.option
                    def _():
                        with self._setname('params'):
                            self._params_(_ss)

                    choice.expecting('<kwparams>', '<params>')
                self._token(']')
                self._define(['kwparams', 'params'], [])

            @choice.option
            def _():
                self._token('(')
                self._cut()
                with self._choice() as choice:
                    @choice.option
                    def _():
                        with self._setname('kwparams'):
                            self._kwparams_(_ss)

                    @choice.option
                    def _():
                        with self._setname('params'):
                            self._params_(_ss)
                        self._token(',')
                        self._cut()
                        with self._setname('kwparams'):
                            self._kwparams_(_ss)
                        self._define(['kwparams', 'params'], [])

                    @choice.option
                    def _():
                        with self._setname('params'):
                            self._params_(_ss)

                    choice.expecting('<kwparams>', '<params>')
                self._token(')')
                self._define(['kwparams', 'params'], [])

            @choice.option
            def _():
                self._token('::')
                self._cut()
                with self._setname('params'):
                    self._params_(_ss)
                self._define(['params'], [])

            choice.expecting('(', '::', '[')

    @rule('Rule')
    def _rule_(self, _ss: Any = None):
        with self._setname('decorators'):

            def block0():
                self._decorator_(_ss)

            self._closure(block0)
        with self._setname('name'):
            self._name_(_ss)
        self._cut()
        with self._optional():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._token('[')
                    self._cut()
                    with self._choice() as choice:
                        @choice.option
                        def _():
                            with self._setname('kwparams'):
                                self._kwparams_(_ss)

                        @choice.option
                        def _():
                            with self._setname('params'):
                                self._params_(_ss)
                            self._token(',')
                            self._cut()
                            with self._setname('kwparams'):
                                self._kwparams_(_ss)
                            self._define(['kwparams', 'params'], [])

                        @choice.option
                        def _():
                            with self._setname('params'):
                                self._params_(_ss)

                        choice.expecting('<kwparams>', '<params>')
                    self._token(']')
                    self._define(['kwparams', 'params'], [])

                @choice.option
                def _():
                    self._token('(')
                    self._cut()
                    with self._choice() as choice:
                        @choice.option
                        def _():
                            with self._setname('kwparams'):
                                self._kwparams_(_ss)

                        @choice.option
                        def _():
                            with self._setname('params'):
                                self._params_(_ss)
                            self._token(',')
                            self._cut()
                            with self._setname('kwparams'):
                                self._kwparams_(_ss)
                            self._define(['kwparams', 'params'], [])

                        @choice.option
                        def _():
                            with self._setname('params'):
                                self._params_(_ss)

                        choice.expecting('<kwparams>', '<params>')
                    self._token(')')
                    self._define(['kwparams', 'params'], [])

                @choice.option
                def _():
                    self._token('::')
                    self._cut()
                    with self._setname('params'):
                        self._params_(_ss)
                    self._define(['params'], [])

                choice.expecting('(', '::', '[')
        with self._optional():
            self._token('<')
            self._cut()
            with self._setname('base'):
                self._known_name_(_ss)
            self._define(['base'], [])
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._token('=')

                @choice.option
                def _():
                    self._token(':=')

                @choice.option
                def _():
                    self._token(':')

                choice.expecting(':', ':=', '=')
        self._cut()
        with self._setname('exp'):
            self._expre_(_ss)
        self._ENDRULE_(_ss)
        self._cut()
        self._define(['base', 'decorators', 'exp', 'kwparams', 'name', 'params'], [])

    @rule()
    def _ENDRULE_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                with self._if():
                    self._UNINDENTED_(_ss)

            @choice.option
            def _():
                self._EMPTYLINE_(_ss)
                with self._optional():
                    self._token(';')

            @choice.option
            def _():
                self._check_eof()

            @choice.option
            def _():
                self._token(';')

            choice.expecting(
                '(?:\\s*(?:\\r?\\n|\\r)){2,}',
                '(?=\\s*(?:\\r?\\n|\\r)[^\\s])',
                ';',
                '<EMPTYLINE>',
                '<UNINDENTED>'
            )

    @rule()
    def _UNINDENTED_(self, _ss: Any = None):
        self._pattern(r'(?=\s*(?:\r?\n|\r)[^\s])')

    @rule()
    def _EMPTYLINE_(self, _ss: Any = None):
        self._pattern(r'(?:\s*(?:\r?\n|\r)){2,}')

    @rule()
    def _decorator_(self, _ss: Any = None):
        self._token('@')
        with self._ifnot():
            self._token('@')
        self._cut()
        with self._setname('@'):
            with self._group():
                with self._choice() as choice:
                    @choice.option
                    def _():
                        self._token('override')

                    @choice.option
                    def _():
                        self._token('name')

                    @choice.option
                    def _():
                        self._token('nomemo')

                    choice.expecting('name', 'nomemo', 'override')

    @rule()
    def _params_(self, _ss: Any = None):
        with self._addname('@'):
            self._first_param_(_ss)

        def block0():
            self._token(',')
            with self._addname('@'):
                self._literal_(_ss)
            with self._ifnot():
                self._token('=')
            self._cut()

        self._closure(block0)

    @rule()
    def _first_param_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                self._path_(_ss)

            @choice.option
            def _():
                self._literal_(_ss)

            choice.expecting(
                '(?!\\d)\\w+(?:::(?!\\d)\\w+)+',
                '<boolean>',
                '<float>',
                '<hex>',
                '<int>',
                '<literal>',
                '<null>',
                '<path>',
                '<raw_string>',
                '<string>',
                '<word>'
            )

    @rule()
    def _kwparams_(self, _ss: Any = None):

        def sep0():
            self._token(',')

        def block1():
            self._pair_(_ss)

        self._positive_gather(block1, sep0)

    @rule()
    def _pair_(self, _ss: Any = None):
        with self._addname('@'):
            self._word_(_ss)
        self._token('=')
        self._cut()
        with self._addname('@'):
            self._literal_(_ss)

    @rule()
    def _expre_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                self._choice_(_ss)

            @choice.option
            def _():
                self._sequence_(_ss)

            choice.expecting(
                ';',
                '<EMPTYLINE>',
                '<ENDRULE>',
                '<UNINDENTED>',
                '<choice>',
                '<element>',
                '<option>',
                '<sequence>',
                '|'
            )

    @rule('Choice')
    def _choice_(self, _ss: Any = None):
        with self._optional():
            self._token('|')
            self._cut()
        with self._addname('@'):
            self._option_(_ss)

        def block0():
            self._token('|')
            self._cut()
            with self._addname('@'):
                self._option_(_ss)

        self._positive_closure(block0)

    @rule('Option')
    def _option_(self, _ss: Any = None):
        with self._setname('@'):
            self._sequence_(_ss)

    @rule('Sequence')
    def _sequence_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                with self._if():
                    with self._group():
                        self._element_(_ss)
                        self._token(',')

                def sep0():
                    self._token(',')

                def block1():
                    self._element_(_ss)

                self._positive_gather(block1, sep0)

            @choice.option
            def _():

                def block2():
                    with self._ifnot():
                        self._ENDRULE_(_ss)
                    self._element_(_ss)

                self._positive_closure(block2)

            choice.expecting(
                '(?:\\s*(?:\\r?\\n|\\r)){2,}',
                '(?=\\s*(?:\\r?\\n|\\r)[^\\s])',
                ';',
                '<EMPTYLINE>',
                '<ENDRULE>',
                '<UNINDENTED>',
                '<element>',
                '<named>',
                '<override>',
                '<rule_include>',
                '<term>'
            )

    @rule()
    def _element_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                self._rule_include_(_ss)

            @choice.option
            def _():
                self._named_(_ss)

            @choice.option
            def _():
                self._override_(_ss)

            @choice.option
            def _():
                self._term_(_ss)

            choice.expecting(
                '<atom>',
                '<closure>',
                '<cut>',
                '<cut_deprecated>',
                '<empty_closure>',
                '<gather>',
                '<join>',
                '<left_join>',
                '<lookahead>',
                '<named>',
                '<named_list>',
                '<named_single>',
                '<negative_lookahead>',
                '<optional>',
                '<override>',
                '<override_list>',
                '<override_single>',
                '<override_single_deprecated>',
                '<positive_closure>',
                '<right_join>',
                '<rule_include>',
                '<skip_to>',
                '<term>',
                '<void>',
                '>'
            )

    @rule('RuleInclude')
    def _rule_include_(self, _ss: Any = None):
        self._token('>')
        self._cut()
        with self._setname('@'):
            self._known_name_(_ss)

    @rule()
    def _named_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                self._named_list_(_ss)

            @choice.option
            def _():
                self._named_single_(_ss)

            choice.expecting('<name>', '<named_list>', '<named_single>')

    @rule('NamedList')
    def _named_list_(self, _ss: Any = None):
        with self._setname('name'):
            self._name_(_ss)
        self._token('+:')
        self._cut()
        with self._setname('exp'):
            self._term_(_ss)
        self._define(['exp', 'name'], [])

    @rule('Named')
    def _named_single_(self, _ss: Any = None):
        with self._setname('name'):
            self._name_(_ss)
        self._token(':')
        self._cut()
        with self._setname('exp'):
            self._term_(_ss)
        self._define(['exp', 'name'], [])

    @rule()
    def _override_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                self._override_list_(_ss)

            @choice.option
            def _():
                self._override_single_(_ss)

            @choice.option
            def _():
                self._override_single_deprecated_(_ss)

            choice.expecting(
                '<override_list>',
                '<override_single>',
                '<override_single_deprecated>',
                '@',
                '@+:',
                '@:'
            )

    @rule('OverrideList')
    def _override_list_(self, _ss: Any = None):
        self._token('@+:')
        self._cut()
        with self._setname('@'):
            self._term_(_ss)

    @rule('Override')
    def _override_single_(self, _ss: Any = None):
        self._token('@:')
        self._cut()
        with self._setname('@'):
            self._term_(_ss)

    @rule('Override')
    def _override_single_deprecated_(self, _ss: Any = None):
        self._token('@')
        self._cut()
        with self._setname('@'):
            self._term_(_ss)

    @rule()
    def _term_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                self._void_(_ss)

            @choice.option
            def _():
                self._gather_(_ss)

            @choice.option
            def _():
                self._join_(_ss)

            @choice.option
            def _():
                self._left_join_(_ss)

            @choice.option
            def _():
                self._right_join_(_ss)

            @choice.option
            def _():
                self._empty_closure_(_ss)

            @choice.option
            def _():
                self._positive_closure_(_ss)

            @choice.option
            def _():
                self._closure_(_ss)

            @choice.option
            def _():
                self._optional_(_ss)

            @choice.option
            def _():
                self._skip_to_(_ss)

            @choice.option
            def _():
                self._lookahead_(_ss)

            @choice.option
            def _():
                self._negative_lookahead_(_ss)

            @choice.option
            def _():
                self._cut_(_ss)

            @choice.option
            def _():
                self._cut_deprecated_(_ss)

            @choice.option
            def _():
                self._atom_(_ss)

            choice.expecting(
                '!',
                '&',
                '(',
                '()',
                '->',
                '<alert>',
                '<atom>',
                '<call>',
                '<closure>',
                '<constant>',
                '<cut>',
                '<cut_deprecated>',
                '<dot>',
                '<empty_closure>',
                '<eof>',
                '<gather>',
                '<group>',
                '<join>',
                '<left_join>',
                '<lookahead>',
                '<negative_lookahead>',
                '<optional>',
                '<pattern>',
                '<positive_closure>',
                '<right_join>',
                '<skip_to>',
                '<token>',
                '<void>',
                '>>',
                '[',
                '{',
                '{}',
                '~'
            )

    @rule('Group')
    def _group_(self, _ss: Any = None):
        self._token('(')
        self._cut()
        with self._setname('@'):
            self._expre_(_ss)
        self._token(')')
        self._cut()

    @rule()
    def _gather_(self, _ss: Any = None):
        with self._if():
            with self._group():
                self._atom_(_ss)
                self._token('.{')
        self._cut()
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._positive_gather_(_ss)

                @choice.option
                def _():
                    self._normal_gather_(_ss)

                choice.expecting('<normal_gather>', '<positive_gather>')

    @rule('PositiveGather')
    def _positive_gather_(self, _ss: Any = None):
        with self._setname('sep'):
            self._atom_(_ss)
        self._token('.{')
        with self._setname('exp'):
            self._expre_(_ss)
        self._token('}')
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._token('+')

                @choice.option
                def _():
                    self._token('-')

                choice.expecting('+', '-')
        self._cut()
        self._define(['exp', 'sep'], [])

    @rule('Gather')
    def _normal_gather_(self, _ss: Any = None):
        with self._setname('sep'):
            self._atom_(_ss)
        self._token('.{')
        self._cut()
        with self._setname('exp'):
            self._expre_(_ss)
        self._token('}')
        with self._optional():
            self._token('*')
            self._cut()
        self._cut()
        self._define(['exp', 'sep'], [])

    @rule()
    def _join_(self, _ss: Any = None):
        with self._if():
            with self._group():
                self._atom_(_ss)
                self._token('%{')
        self._cut()
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._positive_join_(_ss)

                @choice.option
                def _():
                    self._normal_join_(_ss)

                choice.expecting('<normal_join>', '<positive_join>')

    @rule('PositiveJoin')
    def _positive_join_(self, _ss: Any = None):
        with self._setname('sep'):
            self._atom_(_ss)
        self._token('%{')
        with self._setname('exp'):
            self._expre_(_ss)
        self._token('}')
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._token('+')

                @choice.option
                def _():
                    self._token('-')

                choice.expecting('+', '-')
        self._cut()
        self._define(['exp', 'sep'], [])

    @rule('Join')
    def _normal_join_(self, _ss: Any = None):
        with self._setname('sep'):
            self._atom_(_ss)
        self._token('%{')
        self._cut()
        with self._setname('exp'):
            self._expre_(_ss)
        self._token('}')
        with self._optional():
            self._token('*')
            self._cut()
        self._cut()
        self._define(['exp', 'sep'], [])

    @rule('LeftJoin')
    def _left_join_(self, _ss: Any = None):
        with self._setname('sep'):
            self._atom_(_ss)
        self._token('<{')
        self._cut()
        with self._setname('exp'):
            self._expre_(_ss)
        self._token('}')
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._token('+')

                @choice.option
                def _():
                    self._token('-')

                choice.expecting('+', '-')
        self._cut()
        self._define(['exp', 'sep'], [])

    @rule('RightJoin')
    def _right_join_(self, _ss: Any = None):
        with self._setname('sep'):
            self._atom_(_ss)
        self._token('>{')
        self._cut()
        with self._setname('exp'):
            self._expre_(_ss)
        self._token('}')
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._token('+')

                @choice.option
                def _():
                    self._token('-')

                choice.expecting('+', '-')
        self._cut()
        self._define(['exp', 'sep'], [])

    @rule('PositiveClosure')
    def _positive_closure_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                self._token('{')
                with self._setname('@'):
                    self._expre_(_ss)
                self._token('}')
                with self._group():
                    with self._choice() as choice:
                        @choice.option
                        def _():
                            self._token('-')

                        @choice.option
                        def _():
                            self._token('+')

                        choice.expecting('+', '-')
                self._cut()

            @choice.option
            def _():
                with self._setname('@'):
                    self._atom_(_ss)
                self._token('+')
                self._cut()

            choice.expecting(
                '(',
                '<alert>',
                '<atom>',
                '<call>',
                '<constant>',
                '<dot>',
                '<eof>',
                '<group>',
                '<pattern>',
                '<token>',
                '{'
            )

    @rule('Closure')
    def _closure_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                self._token('{')
                with self._setname('@'):
                    self._expre_(_ss)
                self._token('}')
                with self._optional():
                    self._token('*')
                self._cut()

            @choice.option
            def _():
                with self._setname('@'):
                    self._atom_(_ss)
                self._token('*')
                self._cut()

            choice.expecting(
                '(',
                '<alert>',
                '<atom>',
                '<call>',
                '<constant>',
                '<dot>',
                '<eof>',
                '<group>',
                '<pattern>',
                '<token>',
                '{'
            )

    @rule('EmptyClosure')
    def _empty_closure_(self, _ss: Any = None):
        self._token('{}')
        self._cut()
        with self._setname('@'):
            self._void()

    @rule('Optional')
    def _optional_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                self._token('[')
                self._cut()
                with self._setname('@'):
                    self._expre_(_ss)
                self._token(']')
                self._cut()

            @choice.option
            def _():
                with self._setname('@'):
                    self._atom_(_ss)
                with self._ifnot():
                    with self._group():
                        with self._choice() as choice:
                            @choice.option
                            def _():
                                self._token('?"')

                            @choice.option
                            def _():
                                self._token("?'")

                            @choice.option
                            def _():
                                self._token('?/')

                            choice.expecting("?'", '?"', '?/')
                self._token('?')
                self._cut()

            choice.expecting(
                '(',
                '<alert>',
                '<atom>',
                '<call>',
                '<constant>',
                '<dot>',
                '<eof>',
                '<group>',
                '<pattern>',
                '<token>',
                '['
            )

    @rule('Lookahead')
    def _lookahead_(self, _ss: Any = None):
        self._token('&')
        self._cut()
        with self._setname('@'):
            self._term_(_ss)

    @rule('NegativeLookahead')
    def _negative_lookahead_(self, _ss: Any = None):
        self._token('!')
        self._cut()
        with self._setname('@'):
            self._term_(_ss)

    @rule('SkipTo')
    def _skip_to_(self, _ss: Any = None):
        self._token('->')
        self._cut()
        with self._setname('@'):
            self._term_(_ss)

    @rule()
    def _atom_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                self._group_(_ss)

            @choice.option
            def _():
                self._token_(_ss)

            @choice.option
            def _():
                self._alert_(_ss)

            @choice.option
            def _():
                self._constant_(_ss)

            @choice.option
            def _():
                self._call_(_ss)

            @choice.option
            def _():
                self._pattern_(_ss)

            @choice.option
            def _():
                self._dot_(_ss)

            @choice.option
            def _():
                self._eof_(_ss)

            choice.expecting(
                '$',
                '(',
                '/./',
                '<alert>',
                '<call>',
                '<constant>',
                '<dot>',
                '<eof>',
                '<group>',
                '<pattern>',
                '<raw_string>',
                '<regexes>',
                '<string>',
                '<token>',
                '<word>',
                '\\^+',
                '`'
            )

    @rule('Call')
    def _call_(self, _ss: Any = None):
        self._word_(_ss)

    @rule('Void')
    def _void_(self, _ss: Any = None):
        self._token('()')
        self._cut()

    @rule('Fail')
    def _fail_(self, _ss: Any = None):
        self._token('!()')
        self._cut()

    @rule('Cut')
    def _cut_(self, _ss: Any = None):
        self._token('~')
        self._cut()

    @rule('Cut')
    def _cut_deprecated_(self, _ss: Any = None):
        self._token('>>')
        self._cut()

    @rule()
    def _known_name_(self, _ss: Any = None):
        self._name_(_ss)
        self._cut()

    @rule()
    def _name_(self, _ss: Any = None):
        self._word_(_ss)

    @rule('Constant')
    def _constant_(self, _ss: Any = None):
        with self._if():
            self._token('`')
        with self._group():
            with self._choice() as choice:
                @choice.option
                def _():
                    self._pattern(r'(?ms)```((?:.|\n)*?)```')

                @choice.option
                def _():
                    self._token('`')
                    with self._setname('@'):
                        self._literal_(_ss)
                    self._token('`')

                @choice.option
                def _():
                    self._pattern(r'`(.*?)`')

                choice.expecting('(?ms)```((?:.|\\n)*?)```', '`', '`(.*?)`')

    @rule('Alert')
    def _alert_(self, _ss: Any = None):
        with self._setname('level'):
            self._pattern(r'\^+')
        with self._setname('message'):
            self._constant_(_ss)
        self._define(['level', 'message'], [])

    @rule('Token')
    def _token_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                self._string_(_ss)

            @choice.option
            def _():
                self._raw_string_(_ss)

            choice.expecting('<STRING>', '<raw_string>', '<string>', 'r')

    @rule()
    def _literal_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                self._string_(_ss)

            @choice.option
            def _():
                self._raw_string_(_ss)

            @choice.option
            def _():
                self._boolean_(_ss)

            @choice.option
            def _():
                self._word_(_ss)

            @choice.option
            def _():
                self._hex_(_ss)

            @choice.option
            def _():
                self._float_(_ss)

            @choice.option
            def _():
                self._int_(_ss)

            @choice.option
            def _():
                self._null_(_ss)

            choice.expecting(
                '(?!\\d)\\w+',
                '0[xX](?:\\d|[a-fA-F])+',
                '<STRING>',
                '<boolean>',
                '<float>',
                '<hex>',
                '<int>',
                '<null>',
                '<raw_string>',
                '<string>',
                '<word>',
                'False',
                'None',
                'True',
                '[-+]?(?:\\d+\\.\\d*|\\d*\\.\\d+)(?:[Ee][-+]?\\d+)?',
                '[-+]?\\d+',
                'r'
            )

    @rule()
    def _string_(self, _ss: Any = None):
        self._STRING_(_ss)

    @rule()
    def _raw_string_(self, _ss: Any = None):
        self._pattern(r'r')
        with self._setname('@'):
            self._STRING_(_ss)

    @rule()
    def _STRING_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                with self._setname('@'):
                    self._pattern(r'"((?:[^"\n]|\\"|\\\\)*?)"')
                self._cut()

            @choice.option
            def _():
                with self._setname('@'):
                    self._pattern(r"'((?:[^'\n]|\\'|\\\\)*?)'")
                self._cut()

            choice.expecting(
                "'((?:[^'\\n]|\\\\'|\\\\\\\\)*?)'",
                '"((?:[^"\\n]|\\\\"|\\\\\\\\)*?)"'
            )

    @rule()
    def _hex_(self, _ss: Any = None):
        self._pattern(r'0[xX](?:\d|[a-fA-F])+')

    @rule()
    def _float_(self, _ss: Any = None):
        self._pattern(r'[-+]?(?:\d+\.\d*|\d*\.\d+)(?:[Ee][-+]?\d+)?')

    @rule()
    def _int_(self, _ss: Any = None):
        self._pattern(r'[-+]?\d+')

    @rule()
    def _path_(self, _ss: Any = None):
        self._pattern(r'(?!\d)\w+(?:::(?!\d)\w+)+')

    @rule()
    def _word_(self, _ss: Any = None):
        self._pattern(r'(?!\d)\w+')

    @rule('Dot')
    def _dot_(self, _ss: Any = None):
        self._token('/./')

    @rule('Pattern')
    def _pattern_(self, _ss: Any = None):
        self._regexes_(_ss)

    @rule()
    def _regexes_(self, _ss: Any = None):

        def sep0():
            self._token('+')

        def block1():
            self._regex_(_ss)

        self._positive_gather(block1, sep0)

    @rule()
    def _regex_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                self._token('/')
                self._cut()
                with self._setname('@'):
                    self._pattern(r'(?:[^/\\]|\\/|\\.)*')
                self._token('/')
                self._cut()

            @choice.option
            def _():
                self._token('?')
                with self._setname('@'):
                    self._STRING_(_ss)

            @choice.option
            def _():
                self._deprecated_regex_(_ss)

            choice.expecting('/', '<deprecated_regex>', '?', '?/')

    @rule()
    def _deprecated_regex_(self, _ss: Any = None):
        self._token('?/')
        self._cut()
        with self._setname('@'):
            self._pattern(r'(?:.|\n)*?(?=/\?)')
        self._pattern(r'/\?+')
        self._cut()

    @rule()
    def _boolean_(self, _ss: Any = None):
        with self._choice() as choice:
            @choice.option
            def _():
                self._token('True')

            @choice.option
            def _():
                self._token('False')

            choice.expecting('False', 'True')

    @rule()
    def _null_(self, _ss: Any = None):
        self._token('None')

    @rule('EOF')
    def _eof_(self, _ss: Any = None):
        self._token('$')
        self._cut()


def main(filename, **kwargs):
    if not filename or filename == '-':
        import sys

        text = sys.stdin.read()
    else:
        import pathlib

        text = pathlib.Path(filename).read_text()

    parser = TatSuBootstrapParser()
    return parser.parse(text, filename=filename, **kwargs)


if __name__ == '__main__':
    import json
    from tatsu.util import asjson

    ast = generic_main(main, TatSuBootstrapParser, name='TatSuBootstrap')
    data = asjson(ast)
    print(json.dumps(data, indent=2))
