@@grammar::Calc


start
    =
    expression $
    ;


expression
    =
    | addition
    | subtraction
    | term
    ;


addition::Add
    =
    left:expression op:'+' ~ right:term
    ;


subtraction::Subtract
    =
    left:expression op:'-' ~ right:term
    ;


term
    =
    | multiplication
    | division
    | factor
    ;


multiplication::Multiply
    =
    left:term op:'*' ~ right:factor
    ;


division::Divide
    =
    left:term '/' ~ right:factor
    ;


factor
    =
    | subexpression
    | number
    ;


subexpression
    =
    '(' ~ @:expression ')'
    ;


number::Number
    =
    value:/\d+/
    ;
