# Copyright (c) 2017-2026 Juancarlo Añez (apalala@gmail.com)
# SPDX-License-Identifier: BSD-4-Clause
from __future__ import annotations

import itertools
import types
from collections.abc import Callable, Iterator
from typing import Any

from .. import grammars
from ..exceptions import CodegenError
from ..mixins.indent import IndentPrintMixin
from ..objectmodel import Node
from ..util import regexp, safe_name
from ..util.abctools import compress_seq
from ..util.undefined import Undefined
from ..walkers import NodeWalker
from .._version import version, version_info
from ..contexts.protocol import Ctx
from ..parserconfig import ParserConfig

HEADER = """\
    #!/usr/bin/env python3

    # CAVEAT UTILITOR
    #
    #  This file was automatically generated by 竜TatSu v{version}
    #
    #     https://pypi.python.org/pypi/tatsu/
    #
    #  Any changes you make to it will be overwritten the next time
    #  the file is generated.

    # ruff: noqa: RUF100, C405, COM812, I001, F401, F811, PLR1702, PLC2801, SIM117
    # ruff: noqa: PL2401, PLC2402, PLC2403
    # E303
    # fmt: off

    from __future__ import annotations

    import tatsu.decorators as tatsu
    from tatsu.buffering import Buffer
    from tatsu.contexts import Ctx
    from tatsu.infos import ParserConfig
    from tatsu.parsing import NGParser, generic_main
    from tatsu.tokenizing.textlines import TextLinesTokenizer

    __all__ = [
        '{tokenizer_name}',
        '{buffer_name}',
        '{parser_name}',
        '{rules_name}',
        'main',
        ]

"""


NGPARSER_BODY = """\
    config = ParserConfig.new(config, **settings)
    rulessource = {rules_name}()
    assert isinstance(config, ParserConfig)
    tokenizercls = config.tokenizercls or {tokenizer_name}

    super().__init__(rulessource, config=config, tokenizercls=tokenizercls)
"""

FOOTER = """\
def main(filename, **kwargs):
    if not filename or filename == '-':
        import sys

        text = sys.stdin.read()
    else:
        import pathlib

        text = pathlib.Path(filename).read_text()

    parser = {name}Parser()
    return parser.parse(text, filename=filename, **kwargs)


if __name__ == '__main__':
    import json
    from tatsu.util import asjson

    ast = generic_main(main, {name}Parser, name='{name}')
    data = asjson(ast)
    print(json.dumps(data, indent=2))
"""


def pythongen(model: Node, parser_name: str = '') -> str:
    generator = PythonParserGenerator(parser_name=parser_name)
    generator.walk(model)
    return generator.printed_text()


class PythonParserGenerator(IndentPrintMixin, NodeWalker):
    _counter: Iterator[int] = itertools.count()

    def __init__(self, parser_name: str = ''):
        super().__init__()
        self.parser_name = parser_name

    @classmethod
    def _next_n(cls) -> int:
        return next(cls._counter)

    @classmethod
    def _reset_counter(cls):
        cls._counter = itertools.count()

    def walk_default(self, node: Any) -> Any:
        return node

    def walk_Grammar(self, grammar: grammars.Grammar):
        basename = self.parser_name or grammar.name
        self.print(
            HEADER.format(
                basename=basename,
                tokenizer_name=self._tokenizer_name(basename),
                buffer_name=self._buffer_name(basename),
                parser_name=self._parser_name(basename),
                rules_name=self._rules_name(basename),
                version=version,
                version_info=tuple(version_info),
            ),
        )
        self.print()
        self.print()

        self._gen_keywords(grammar)
        self._gen_buffering(grammar, basename)
        self._gen_parsing(grammar, basename)

        self.print(FOOTER.format(name=basename).rstrip())

    def walk_Rule(self, rule: grammars.Rule):
        def param_repr(p):
            if isinstance(p, int | float):
                return str(p)
            else:
                return repr(p.split('::')[0])

        self._reset_counter()
        params = kwparams = ''
        if rule.params:
            params = ', '.join(param_repr(self.walk(p)) for p in rule.params)
        if rule.kwparams:
            assert isinstance(rule.kwparams, dict)
            kwparams = ', '.join(
                f'{k}={param_repr(self.walk(v))}' for k, v in rule.kwparams.items()
            )

        if params and kwparams:
            params = params + ', ' + kwparams
        elif kwparams:
            params = kwparams

        leftrec = '\n@tatsu.leftrec' if rule.is_leftrec else ''
        nomemo = '\n@tatsu.nomemo' if not rule.is_memoizable and not leftrec else ''
        isname = '\n@tatsu.name' if rule.is_name else ''

        name = safe_name(rule.name)
        self.print(f"""
                @tatsu.rule({params})\
                {leftrec}\
                {nomemo}\
                {isname}\
                \ndef {name}(self, ctx: Ctx):
            """)
        with self.indent():
            self.print(self.walk(rule.exp))

    def walk_BasedRule(self, rule: grammars.BasedRule):
        self.walk_Rule(rule)

    def walk_Call(self, call: grammars.Call):
        name = safe_name(call.name)
        self.print(f'self.{name}(ctx)')

    def walk_RuleInclude(self, include: grammars.RuleInclude):
        self.walk(include.rule.exp)

    def walk_Void(self, _void: grammars.Void):
        self.print('ctx.void()')

    def walk_Dot(self, _dot: grammars.Dot):
        self.print('ctx.dot()')

    def walk_Fail(self, _fail: grammars.Fail):
        self.print('ctx.fail()')

    def walk_Cut(self, _cut: grammars.Cut):
        self.print('ctx.cut()')

    def walk_Comment(self, comment: grammars.Comment):
        lines = '\n'.join(f'# {c!s}' for c in comment.comment.splitlines())
        self.print(f'\n{lines}\n')

    def walk_EOLComment(self, comment: grammars.EOLComment):
        self.walk_Comment(comment)

    def walk_EOF(self, _eof: grammars.EOF):
        self.print('ctx.eofcheck()')

    def walk_Group(self, group: grammars.Group):
        self._gen_decor(Ctx.group, group.exp)

    def walk_Token(self, token: grammars.Token):
        self.print(f'ctx.token({token.token!r})')

    def walk_Constant(self, constant: grammars.Constant):
        self.print(f'ctx.constant({constant.literal!r})')

    def walk_Alert(self, alert: grammars.Alert):
        self.print(f'ctx.alert({alert.literal!r}, {alert.level})')

    def walk_Pattern(self, pattern: grammars.Pattern):
        self.print(f'ctx.pattern({regexp(pattern.pattern)})')

    def walk_Lookahead(self, lookahead: grammars.Lookahead):
        self._gen_decor(Ctx.if_, lookahead.exp)

    def walk_NegativeLookahead(self, lookahead: grammars.NegativeLookahead):
        self._gen_decor(Ctx.ifnot_, lookahead.exp)

    def walk_Sequence(self, seq: grammars.Sequence):
        self._gen_defines_declaration(seq)
        self.walk(seq.sequence)

    def walk_Choice(self, choice: grammars.Choice):
        if len(choice.options) == 1:
            self.walk(choice.options[0])
            return

        self._gen_decor(Ctx.choice, var='ch')
        with self.indent():
            self.walk(choice.options)

        elements = sorted(repr(f[0]) for f in choice.lookahead() if f)
        if not elements:
            return

        with self.indent():
            expectstr = f'ch.expecting({', '.join(elements)})'
            if self.fitsfmt(expectstr, 3):
                self.print(expectstr)
            else:
                self.print('ch.expecting(')
                with self.indent():
                    expectinner = ',\n'.join(elements)
                    self.print(expectinner)
                self.print(')')

    def walk_Option(self, option: grammars.Option):
        self._gen_anon_block(option.exp, decor='ch.option')
        self.print()

    def walk_Optional(self, optional: grammars.Optional):
        self._gen_decor(Ctx.optional, optional.exp)

    def walk_EmptyClosure(self, _closure: grammars.EmptyClosure):
        self.print('ctx.empty()')

    def walk_Closure(self, closure: grammars.Closure):
        self._gen_decor(Ctx.loopopt, closure.exp, var='cl')

    def walk_PositiveClosure(self, closure: grammars.PositiveClosure):
        self._gen_decor(Ctx.loopplus, closure.exp, var='cl')

    def walk_Join(self, join: grammars.Join):
        self._gen_decor(Ctx.joinopt, join.exp, sep=join.sep, var='cl')

    def walk_PositiveJoin(self, join: grammars.PositiveJoin):
        self._gen_decor(Ctx.joinplus, join.exp, sep=join.sep, var='cl')

    def walk_LeftJoin(self, join: grammars.LeftJoin):
        self._gen_decor(Ctx.joinleft, join.exp, sep=join.sep, var='cl')

    def walk_RightJoin(self, join: grammars.RightJoin):
        self._gen_decor(Ctx.joinright, join.exp, sep=join.sep, var='cl')

    def walk_Gather(self, gather: grammars.Gather):
        self._gen_decor(Ctx.gatheropt, gather.exp, sep=gather.sep, var='g')

    def walk_PositiveGather(self, gather: grammars.PositiveGather):
        self._gen_decor(Ctx.gatherplus, gather.exp, sep=gather.sep, var='g')

    def walk_SkipTo(self, skipto: grammars.SkipTo):
        self._gen_decor(Ctx.skipto, skipto.exp)

    def walk_Named(self, named: grammars.Named):
        self._gen_decor(Ctx.nameset, named.exp, arg=repr(named.name))

    def walk_NamedList(self, named: grammars.Named):
        self._gen_decor(Ctx.nameadd, named.exp, arg=repr(named.name))

    def walk_Override(self, override: grammars.Override):
        self.walk_Named(override)

    def walk_OverrideList(self, override: grammars.OverrideList):
        self.walk_NamedList(override)

    def _gen_keywords(self, grammar: grammars.Grammar):
        keywords = [str(k) for k in grammar.keywords if k is not None]
        if not keywords:
            self.print('KEYWORDS: set[str] = set()')
        else:
            self.print('KEYWORDS: set[str] = {')
            with self.indent():
                keywords_str = '\n'.join(f'    {k!r},' for k in sorted(keywords))
                self.print(keywords_str)
            self.print('}')

        self.print()
        self.print()

    def _gen_init(self, grammar: grammars.Grammar):
        assert isinstance(grammar.config, ParserConfig)
        start = grammar.config.start or grammar.rules[0].name

        whitespace = grammar.config.whitespace
        if whitespace is Undefined:  # the default value
            whitespace = None
        elif whitespace is not None:
            whitespace = regexp(whitespace)

        self.print(f'''
                config = ParserConfig.new(
                    config=config,
                    whitespace={whitespace},
                    nameguard={grammar.config.nameguard},
                    ignorecase={grammar.config.ignorecase or False},
                    namechars={grammar.config.namechars or ""!r},
                    parseinfo={grammar.config.parseinfo},
                    comments={regexp(grammar.config.comments)},
                    eol_comments={regexp(grammar.config.eol_comments)},
                    keywords=KEYWORDS,
                    start={start!r},
                )
                assert isinstance(config, ParserConfig)
                config = config.override(**settings)
            ''')

    def _tokenizer_name(self, basename) -> str:
        return f'{basename}Tokenizer'

    def _buffer_name(self, basename) -> str:
        return f'{basename}Buffer'

    def _parser_name(self, basename: str) -> str:
        return f'{basename}Parser'

    def _rules_name(self, basename: str) -> str:
        return f'{basename}Rules'

    def _gen_buffering_init(self, grammar: grammars.Grammar):
        with self.indent():
            self.print('def __init__(')
            with self.indent():
                self.print(
                    """
                    self,
                    text, /,
                    config: ParserConfig | None = None,
                    **settings,
                    """,
                )
            self.print(') -> None:')
            with self.indent():
                self._gen_init(grammar)
                self.print()
                self.print('super().__init__(text, config=config)')
        self.print()

    def _gen_buffering(self, grammar: grammars.Grammar, basename: str):
        self.print(f'class {self._tokenizer_name(basename)}(TextLinesTokenizer):')
        self._gen_buffering_init(grammar)

        self.print()
        self.print(
            f'class {self._buffer_name(basename)}(Buffer):  # NOTE: backwards compatibility'
        )
        self._gen_buffering_init(grammar)
        self.print()

    def _gen_parsing(self, grammar: grammars.Grammar, basename: str):
        self.print(f'class {self._parser_name(basename)}(NGParser):')
        with self.indent():
            self.print(
                'def __init__(self, /, config: ParserConfig | None = None, **settings):'
            )
            with self.indent():
                self.print(
                    '\n'
                    + NGPARSER_BODY.format(
                        parser_name=self._parser_name(basename),
                        rules_name=self._rules_name(basename),
                        tokenizer_name=self._tokenizer_name(basename),
                    )
                )
        self.print()
        self.print()

        self.print(f'class {self._rules_name(basename)}:')
        with self.indent():
            self.print(
                'def __init__(self, /, config: ParserConfig | None = None, **settings):',
            )
            with self.indent():
                self._gen_init(grammar)
                self.print('self._config = config')
                self.print()
            self.print("""
                @property
                def config(self) -> ParserConfig:
                    assert isinstance(self._config, ParserConfig)
                    return self._config
                """)
            self.print()
            self.walk(grammar.rules)
        self.print()

    def _gen_defines_declaration(self, node: grammars.Model):
        defines = compress_seq(node.defines())
        ldefs = {safe_name(d) for d, value in defines if value}
        sdefs = {safe_name(d) for d, value in defines if not value and d not in ldefs}

        if not (sdefs or ldefs):
            return

        sdefs_str = ', '.join(sorted(repr(d) for d in sdefs))
        ldefs_str = ', '.join(sorted(repr(d) for d in ldefs))

        definestr = f'ctx.define([{sdefs_str}], [{ldefs_str}])'
        if not ldefs or self.fitsfmt(definestr, 1):
            self.print(definestr)
        else:
            self.print('ctx.define(')
            with self.indent():
                self.print(f'[{sdefs_str}],')
                self.print(f'[{ldefs_str}],')
            self.print(')')

    def _gen_block(self, exp: grammars.Model, name='block'):
        if () in exp.lookahead():
            raise CodegenError(
                f'{exp!r} may repeat empty sequence @{exp.line} {exp.lookahead()!r}',
            )

        n = self._next_n()
        self.print()
        self.print(f'def {name}{n}():')
        with self.indent():
            self.walk(exp)

        return n

    def _gen_anon_block(
        self,
        exp: grammars.Model,
        decor: str = '',
        echeck: bool = False,
    ):
        if echeck and () in exp.lookahead():
            raise CodegenError(
                f'{exp!r} may repeat empty sequence @{exp.line} {exp.lookahead()!r}',
            )

        if decor:
            self.print(f'@{decor}')
        self.print('def _():')
        with self.indent():
            self.walk(exp)

    def _gen_decor(
        self,
        mgr: Callable[..., Any],
        exp: grammars.Model | None = None,
        sep: grammars.Model | None = None,
        var: str = '',
        arg: str = '',
        echeck: bool = True,
    ):
        assert isinstance(mgr, types.FunctionType)
        name = mgr.__name__
        if var:
            self.print(f'with ctx.{name}({arg}) as {var}:')
        else:
            self.print(f'with ctx.{name}({arg}):')
        with self.indent():
            if sep:
                self._gen_anon_block(sep, decor=f'{var}.sep', echeck=echeck)
                self.print()
            if exp and var:
                self._gen_anon_block(exp, decor=f'{var}.exp', echeck=echeck)
            elif exp:
                self.walk(exp)
