#!/usr/bin/env python3
# copyright: ignore
#
# CAVEAT UTILITOR
#
#  This file was automatically generated by 竜TatSu v5.18.0b1
#
#     https://pypi.python.org/pypi/tatsu/
#
#  Any changes you make to it will be overwritten the next time
#  the file is generated.
#
# ruff: noqa
# ty: ignore
# mypy: ignore-errors
# pyright: ignore
# type: ignore
# noqa
# fmt: off

from __future__ import annotations

from tatsu import decorators as tatsu
from tatsu.contexts import Ctx
from tatsu.parserconfig import ParserConfig
from tatsu.parsing import Parser, generic_main
from tatsu.tokenizing.buffer import Buffer
from tatsu.tokenizing.textlines import TextLinesTokenizer


KEYWORDS: set[str] = set()


class LISPTokenizer(TextLinesTokenizer):
    def __init__(
        self,
        text, /,
        config: ParserConfig | None = None,
        **settings,
    ) -> None:
        config = ParserConfig.new(
            config=config,
            whitespace=None,
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=False,
            comments=r'None',
            eol_comments=r'None',
            keywords=KEYWORDS,
            start='start',
        )
        assert isinstance(config, ParserConfig)
        config = config.override(**settings)

        super().__init__(text, config=config)


class LISPBuffer(Buffer):  # NOTE: backwards compatibility
    def __init__(
        self,
        text, /,
        config: ParserConfig | None = None,
        **settings,
    ) -> None:
        config = ParserConfig.new(
            config=config,
            whitespace=None,
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=False,
            comments=r'None',
            eol_comments=r'None',
            keywords=KEYWORDS,
            start='start',
        )
        assert isinstance(config, ParserConfig)
        config = config.override(**settings)

        super().__init__(text, config=config)


class LISPParser(Parser):
    def __init__(self, /, config: ParserConfig | None = None, **settings):
        config = ParserConfig.new(config, **settings)
        rulessource = LISPRules()
        assert isinstance(config, ParserConfig)
        tokenizercls = config.tokenizercls or LISPTokenizer

        super().__init__(rulessource, config=config, tokenizercls=tokenizercls)


class LISPRules:
    def __init__(self, /, config: ParserConfig | None = None, **settings):
        config = ParserConfig.new(
            config=config,
            whitespace=None,
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=False,
            comments=r'None',
            eol_comments=r'None',
            keywords=KEYWORDS,
            start='start',
        )
        assert isinstance(config, ParserConfig)
        config = config.override(**settings)
        self._config = config

    @property
    def config(self) -> ParserConfig:
        assert isinstance(self._config, ParserConfig)
        return self._config

    @tatsu.rule
    def start(self, ctx: Ctx):
        with ctx.choice() as α:
            α.expecting(
              '<lisp>',
              '<list_>',
              '<number>',
              '<sexp>',
              '<symbol>'
            )

            @α.option
                def 〇(ctx: Ctx):
                self.lisp(ctx)

    @tatsu.rule
    def lisp(self, ctx: Ctx):
        with ctx.choice() as α:
            α.expecting(
              '(',
              '[_\\w][_\\w\\d]*',
              '\\d+(?:\\.\\d+)',
              '<list_>',
              '<number>',
              '<sexp>',
              '<symbol>'
            )

            @α.option
            def 〇(ctx: Ctx):
                self.sexp(ctx)
            @α.option
            def 〇(ctx: Ctx):
                self.list_(ctx)
            @α.option
            def 〇(ctx: Ctx):
                self.symbol(ctx)
            @α.option
            def 〇(ctx: Ctx):
                self.number(ctx)

    @tatsu.rule('SExp')
    def sexp(self, ctx: Ctx):
        with ctx.choice() as α:
            α.expecting('(')

            @α.option
            def 〇(ctx: Ctx):
                ctx.define(['cdr', 'cons'], [])
                ctx.token('(')
                with ctx.nameset('cons'):
                    self.lisp(ctx)
                ctx.token('.')
                ctx.cut()
                with ctx.nameset('cdr'):
                    self.lisp(ctx)
                ctx.token(')')

    @tatsu.rule('List')
    def list_(self, ctx: Ctx):
        with ctx.choice() as α:
            α.expecting('(')

            @α.option
            def 〇(ctx: Ctx):
                ctx.token('(')
                with ctx.nameset('@'):
                    with ctx.loopopt() as cl:
                        @cl.exp
                        def 〇(ctx: Ctx):
                            self.lisp(ctx)
                ctx.token(')')

    @tatsu.rule('Symbol')
    def symbol(self, ctx: Ctx):
        with ctx.choice() as α:
            α.expecting('[_\\w][_\\w\\d]*')

            @α.option
            def 〇(ctx: Ctx):
                ctx.pattern(r'[_\w][_\w\d]*')

    @tatsu.rule('Number')
    def number(self, ctx: Ctx):
        with ctx.choice() as α:
            α.expecting('\\d+(?:\\.\\d+)')

            @α.option
            def 〇(ctx: Ctx):
                ctx.pattern(r'\d+(?:\.\d+)')


def main(filename, **kwargs):
    if not filename or filename == '-':
        import sys

        text = sys.stdin.read()
    else:
        import pathlib

        text = pathlib.Path(filename).read_text()

    parser = LISPParser()
    return parser.parse(text, filename=filename, **kwargs)


if __name__ == '__main__':
    import json
    from tatsu.util import asjson

    ast = generic_main(main, LISPParser, name='LISP')
    data = asjson(ast)
    print(json.dumps(data, indent=2))
